'use client';
import { useState } from 'react';
import Link from 'next/link';
import { MapPin, Plus, Pencil, Trash2, Check } from 'lucide-react';
import { useApp, useData, api, send, Modal, Loading, Empty, ErrorBox, type Item } from './shared';
export const addressText=(a:Item)=>`${a.line1}, ${a.subdistrict}, ${a.district}, ${a.province} ${a.postcode}`;
export function AddressForm({address,onClose,onSaved}:{address:Item,onClose:()=>void,onSaved:(id:string)=>void}){
 const {user}=useApp();const [value,setValue]=useState<Item>({recipient:user?.name||'',phone:'',line1:'',province:'',district:'',subdistrict:'',postcode:'',label:'home',is_default:false,...address});const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const provinces=useData('geography');const geo=useData(`geography?${new URLSearchParams({province:value.province,district:value.district,subdistrict:value.subdistrict})}`);
 const field=(key:string,v:any)=>setValue(s=>({...s,[key]:v}));
 return <Modal title={address.id?'แก้ไขที่อยู่จัดส่ง':'เพิ่มที่อยู่ใหม่'} onClose={onClose}><form className="form-grid address-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const d=await send(address.id?`addresses/${address.id}`:'addresses',value,address.id?'PATCH':'POST');onSaved(d.id);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>
 <label className="field-label">ชื่อผู้รับ<input required minLength={2} maxLength={100} value={value.recipient} autoComplete="name" onChange={e=>field('recipient',e.target.value)}/></label>
 <label className="field-label">เบอร์โทรศัพท์<input required type="tel" pattern="0[0-9]{8,9}" value={value.phone} autoComplete="tel" onChange={e=>field('phone',e.target.value)}/></label>
 <label className="field-label span-2">บ้านเลขที่ / อาคาร / ถนน<textarea required minLength={5} maxLength={300} rows={2} autoComplete="street-address" value={value.line1} onChange={e=>field('line1',e.target.value)} placeholder="บ้านเลขที่ หมู่ ซอย ถนน อาคาร ชั้น ห้อง"/></label>
 <label className="field-label">จังหวัด<select aria-label="จังหวัด" required value={value.province} onChange={e=>setValue(v=>({...v,province:e.target.value,district:'',subdistrict:'',postcode:''}))}><option value="">เลือกจังหวัด</option>{provinces.data?.provinces.map((p:string)=><option key={p}>{p}</option>)}</select></label>
 <label className="field-label">อำเภอ / เขต<select aria-label="อำเภอ / เขต" required disabled={!value.province} value={value.district} onChange={e=>setValue(v=>({...v,district:e.target.value,subdistrict:'',postcode:''}))}><option value="">เลือกอำเภอ / เขต</option>{geo.data?.districts.map((p:string)=><option key={p}>{p}</option>)}</select></label>
 <label className="field-label">ตำบล / แขวง<select aria-label="ตำบล / แขวง" required disabled={!value.district} value={value.subdistrict} onChange={async e=>{const subdistrict=e.target.value;setValue(v=>({...v,subdistrict,postcode:''}));try{const d=await api(`geography?${new URLSearchParams({province:value.province,district:value.district,subdistrict})}`);setValue(v=>v.province===value.province&&v.district===value.district&&v.subdistrict===subdistrict?{...v,postcode:d.postcodes.length===1?d.postcodes[0]:''}:v);}catch{setError('โหลดรหัสไปรษณีย์ไม่สำเร็จ กรุณาเลือกตำบลอีกครั้ง');}}}><option value="">เลือกตำบล / แขวง</option>{geo.data?.subdistricts.map((p:string)=><option key={p}>{p}</option>)}</select></label>
 <label className="field-label">รหัสไปรษณีย์<select aria-label="รหัสไปรษณีย์" required disabled={!value.subdistrict} value={value.postcode} onChange={e=>field('postcode',e.target.value)}><option value="">เลือกรหัสไปรษณีย์</option>{geo.data?.postcodes.map((p:string)=><option key={p}>{p}</option>)}</select></label>
 <fieldset className="address-labels span-2"><legend>บันทึกเป็น</legend>{[['home','บ้าน'],['work','ที่ทำงาน'],['other','อื่น ๆ']].map(([key,name])=><label key={key} className={value.label===key?'selected':''}><input type="radio" name="address-label" value={key} checked={value.label===key} onChange={()=>field('label',key)}/>{name}</label>)}</fieldset>
 <label className="check-label span-2"><input type="checkbox" checked={value.is_default} onChange={e=>field('is_default',e.target.checked)}/>ตั้งเป็นที่อยู่เริ่มต้น</label><div className="span-2"><ErrorBox text={error||geo.error||provinces.error}/><div className="address-form-actions"><button type="button" className="button" onClick={onClose} disabled={busy}>ยกเลิก</button><button className="button primary" disabled={busy}>{busy?'กำลังบันทึก…':'บันทึกที่อยู่'}</button></div></div></form></Modal>;
}
export function AddressRows({items,selected,onSelect,onEdit,onDelete,onDefault,busy=false}:{items:Item[],selected?:string,onSelect?:(id:string)=>void,onEdit:(a:Item)=>void,onDelete?:(a:Item)=>void,onDefault?:(a:Item)=>void,busy?:boolean}){return <div className="address-list">{items.map(a=><div className={`saved-address ${selected===a.id?'chosen':''}`} key={a.id}>{onSelect&&<input type="radio" name="shipping-address" checked={selected===a.id} onChange={()=>onSelect(a.id)} aria-label={`เลือกที่อยู่ ${a.recipient} ${a.line1}`}/>}<div className="saved-address-body"><div className="address-name"><strong>{a.recipient}</strong><span>{a.phone}</span>{a.is_default&&<span className="default-tag">ค่าเริ่มต้น</span>}</div><p>{addressText(a)}</p><span className="address-label">{{home:'บ้าน',work:'ที่ทำงาน',other:'อื่น ๆ'}[a.label as string]}</span><div className="address-actions"><button type="button" className="text-link" disabled={busy} onClick={()=>onEdit(a)}><Pencil size={14}/>แก้ไข</button>{onDefault&&!a.is_default&&<button type="button" className="text-link" disabled={busy} onClick={()=>onDefault(a)}>ตั้งเป็นค่าเริ่มต้น</button>}{onDelete&&<button type="button" className="text-link danger" disabled={busy} onClick={()=>onDelete(a)}><Trash2 size={14}/>ลบ</button>}</div></div></div>)}</div>;}
export function AddressPage(){const {user,session}=useApp();if(!session)return <Loading/>;if(!user)return <Empty title="เข้าสู่ระบบเพื่อจัดการที่อยู่"><Link className="button primary" href="/login">เข้าสู่ระบบ</Link></Empty>;return <AddressManager/>;}
function AddressManager(){const {data,error,reload}=useData('addresses');const {notify}=useApp();const [edit,setEdit]=useState<Item|null>(null);const [busy,setBusy]=useState(false);const [actionError,setActionError]=useState('');const change=async(a:Item,remove=false)=>{if(remove&&!confirm('ลบที่อยู่นี้จากสมุดที่อยู่?'))return;setBusy(true);setActionError('');try{if(remove)await api(`addresses/${a.id}`,{method:'DELETE'});else await send(`addresses/${a.id}`,{...a,is_default:true},'PATCH');reload();notify(remove?'ลบที่อยู่แล้ว':'ตั้งที่อยู่เริ่มต้นแล้ว');}catch(e:any){setActionError(e.message);}finally{setBusy(false);}};return <div className="narrow"><div className="page-heading section-heading"><div><span className="eyebrow">MY ADDRESSES</span><h1>ที่อยู่ของฉัน</h1><p>บันทึกที่อยู่ไว้ เลือกใช้ได้ทุกครั้งที่สั่งซื้อ</p></div><button className="button primary" onClick={()=>setEdit({})}><Plus size={18}/>เพิ่มที่อยู่ใหม่</button></div><ErrorBox text={error||actionError}/>{!data&&!error?<Loading/>:data?.items.length?<AddressRows items={data.items} onEdit={setEdit} onDelete={a=>change(a,true)} onDefault={a=>change(a)} busy={busy}/>:<Empty title="ยังไม่มีที่อยู่จัดส่ง"><button className="button" onClick={()=>setEdit({})}>เพิ่มที่อยู่แรก</button></Empty>}{edit&&<AddressForm address={edit} onClose={()=>setEdit(null)} onSaved={()=>{setEdit(null);reload();notify('บันทึกที่อยู่แล้ว');}}/>}</div>;}
