'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { MapPin, Plus, Truck, ShieldCheck, QrCode, Landmark, ShoppingBag, Check, Trash2, ChevronRight } from 'lucide-react';
import { useApp, useData, api, send, money, Badge, Loading, Empty, ErrorBox, Modal, type Item } from './shared';
import { AddressForm, AddressRows, addressText } from './addresses';
export function CheckoutPage(){const {user,session,cart}=useApp();if(!session)return <Loading/>;if(!cart.length)return <Empty title="ตะกร้าของคุณยังว่าง"><p>เลือกผลงานชิ้นโปรด แล้วกลับมาชำระเงินได้ที่นี่</p><Link className="button primary" href="/">สำรวจผลงาน</Link></Empty>;if(!user)return <Empty title="เข้าสู่ระบบเพื่อดำเนินการสั่งซื้อ"><p>รายการ {cart.length} ชิ้นยังอยู่ในตะกร้าของคุณ</p><Link className="button primary" href="/login">เข้าสู่ระบบ</Link></Empty>;return <CheckoutBody/>;}
function CheckoutBody(){
 const {cart,setCart,notify,user}=useApp();const router=useRouter();const [items,setItems]=useState<Item[]|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [selected,setSelected]=useState('');const [edit,setEdit]=useState<Item|null>(null);const [choosing,setChoosing]=useState(false);const [method,setMethod]=useState('promptpay');const [note,setNote]=useState('');const [key]=useState(()=>crypto.randomUUID());
 const addresses=useData(`addresses?account=${user.id}`);const payment=useData('payment_options');
 useEffect(()=>{let live=true;setItems(null);Promise.all(cart.map((id:string)=>api(`artworks/${id}`).then(d=>d.artwork).catch(()=>({id,missing:true})))).then(v=>{if(live)setItems(v);});return()=>{live=false;};},[cart]);
 useEffect(()=>{if(addresses.data&&!addresses.data.items.some((a:Item)=>a.id===selected))setSelected(addresses.data.items[0]?.id||'');},[addresses.data]);
 useEffect(()=>{if(payment.data&&!payment.data.methods.some((m:Item)=>m.id===method&&m.enabled))setMethod(payment.data.methods.find((m:Item)=>m.enabled)?.id||'');},[payment.data,method]);
 const address=addresses.data?.items.find((a:Item)=>a.id===selected);const total=items?.reduce((s,a)=>s+(Number(a.price)||0),0)||0;const invalid=items?.some(a=>a.missing||a.status!=='approved');
 const checkout=async()=>{setError('');if(!address){setError('กรุณาเพิ่มหรือเลือกที่อยู่จัดส่ง');return;}setBusy(true);try{const d=await send('orders',{artwork_ids:cart,address_id:selected,payment_method:method,buyer_note:note,idempotency_key:key});setCart([]);notify('สร้างคำสั่งซื้อแล้ว กรุณาชำระเงินและแนบสลิป');router.push(`/orders/${d.id}`);}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 return <div className="market-checkout"><div className="checkout-heading"><div><span className="eyebrow">CHECKOUT</span><h1>ชำระเงิน</h1></div><ol className="checkout-steps"><li><Check size={15}/>ตะกร้า</li><ChevronRight size={14}/><li className="current">2 · ที่อยู่และชำระเงิน</li><ChevronRight size={14}/><li>3 · รอตรวจสอบ</li></ol></div>
 <section className="shipping-address panel"><div className="section-heading"><h2><MapPin size={22}/>ที่อยู่ในการจัดส่ง</h2><Link className="text-link" href="/addresses">จัดการที่อยู่</Link></div><ErrorBox text={addresses.error}/>{!addresses.data&&!addresses.error?<Loading/>:address?<div className="selected-address"><div><div className="address-name"><strong>{address.recipient}</strong><span>{address.phone}</span>{address.is_default&&<span className="default-tag">ค่าเริ่มต้น</span>}</div><p>{addressText(address)}</p></div><button className="text-link" onClick={()=>setChoosing(true)} disabled={busy}>เปลี่ยน</button></div>:<button className="button" onClick={()=>setEdit({})}><Plus size={18}/>เพิ่มที่อยู่จัดส่ง</button>}</section>
 <div className="checkout-columns"><div><section className="panel checkout-products"><div className="section-heading"><h2><ShoppingBag size={21}/>สินค้าที่สั่งซื้อ</h2><span className="muted">{cart.length} ชิ้น</span></div>{!items?<Loading/>:items.map(a=><div className="checkout-product" key={a.id}>{!a.missing&&<Link href={`/artworks/${a.id}`}><img src={a.image} alt={a.title}/></Link>}<div><small>{a.artist_name}</small><h3>{a.title||'ไม่พบผลงานนี้'}</h3>{!a.missing&&<p>{a.technique} · {Number(a.width)} × {Number(a.height)} ซม.</p>}<span className="muted">จำนวน 1 ชิ้น</span>{a.status!=='approved'&&!a.missing&&<Badge status={a.status}/>}</div><div className="checkout-product-price"><strong>{money(a.price||0)}</strong><button className="icon-button danger" aria-label={`นำ ${a.title||'ผลงาน'} ออกจากตะกร้า`} disabled={busy} onClick={()=>setCart(cart.filter((id:string)=>id!==a.id))}><Trash2 size={16}/></button></div></div>)}<div className="shipping-method"><Truck size={20}/><div><strong>จัดส่งมาตรฐาน</strong><p>ศิลปินจัดเตรียมผลงานหลังยืนยันการชำระเงิน</p></div><strong>ฟรี</strong></div><label className="field-label buyer-note">ข้อความถึงร้าน<textarea rows={2} maxLength={300} value={note} onChange={e=>setNote(e.target.value)} placeholder="เช่น กรุณาห่อกันกระแทกเป็นพิเศษ"/></label></section>
 <section className="panel checkout-payments"><h2><QrCode size={22}/>วิธีการชำระเงิน</h2><ErrorBox text={payment.error}/>{!payment.data&&!payment.error?<Loading/>:<fieldset className="payment-choices"><legend className="sr-only">เลือกวิธีชำระเงิน</legend>{payment.data?.methods.map((m:Item)=>{const Icon=m.id==='promptpay'?QrCode:Landmark;return <label key={m.id} className={`payment-choice ${method===m.id?'selected':''} ${!m.enabled?'unavailable':''}`}><input type="radio" name="payment-method" value={m.id} checked={method===m.id} disabled={!m.enabled||busy} onChange={()=>setMethod(m.id)}/><Icon size={25}/><span><strong>{m.name}</strong><small>{m.enabled?m.description:'ร้านยังไม่เปิดใช้ช่องทางนี้'}</small></span>{method===m.id&&<Check size={18} className="payment-check"/>}</label>;})}</fieldset>}{payment.data?.demo&&<p className="notice">โหมดทดลอง — ใช้ทดสอบขั้นตอนเท่านั้น ไม่ต้องโอนเงินจริง</p>}<p className="payment-instruction">ข้อมูลสำหรับโอนเงินจะแสดงหลังยืนยันคำสั่งซื้อ เมื่อแนบสลิปแล้ว แอดมินจะตรวจสอบยอดก่อนจัดส่ง</p></section></div>
 <aside className="panel checkout-summary"><span className="eyebrow">ORDER SUMMARY</span><h2>สรุปคำสั่งซื้อ</h2><dl><div><dt>ยอดรวมสินค้า ({cart.length} ชิ้น)</dt><dd>{money(total)}</dd></div><div><dt>ค่าจัดส่ง</dt><dd className="free-shipping">ฟรี</dd></div></dl><div className="checkout-grand-total"><span>ยอดชำระทั้งหมด</span><strong>{money(total)}</strong></div><p className="summary-method">{payment.data?.methods.find((m:Item)=>m.id===method)?.name||'ยังไม่มีช่องทางชำระเงิน'}</p><ErrorBox text={error|| (invalid?'มีผลงานที่ไม่พร้อมจำหน่าย กรุณานำออกจากตะกร้า':'')}/><button className="button primary full" onClick={checkout} disabled={busy||!items||invalid||!address||!method}>{busy?'กำลังสร้างคำสั่งซื้อ…':'ยืนยันคำสั่งซื้อ'}</button><p className="checkout-trust"><ShieldCheck size={17}/>ตรวจสอบที่อยู่และยอดเงินก่อนยืนยัน</p><Link href="/" className="checkout-back">เลือกดูผลงานเพิ่มเติม</Link></aside></div>
 {choosing&&!edit&&<Modal title="เลือกที่อยู่จัดส่ง" onClose={()=>setChoosing(false)}><AddressRows items={addresses.data?.items||[]} selected={selected} onSelect={setSelected} onEdit={setEdit}/><div className="address-form-actions"><button className="button" onClick={()=>setEdit({})}><Plus size={17}/>เพิ่มที่อยู่ใหม่</button><button className="button primary" onClick={()=>setChoosing(false)}>ใช้ที่อยู่นี้</button></div></Modal>}
 {edit&&<AddressForm address={edit} onClose={()=>setEdit(null)} onSaved={id=>{setEdit(null);setChoosing(false);setSelected(id);addresses.reload();notify('บันทึกที่อยู่จัดส่งแล้ว');}}/>}</div>;
}
