'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { Asterisk, ShoppingBag, ArrowUpRight, ArrowRight, Search, SlidersHorizontal, LayoutGrid, List, UserRound, LogOut, Menu, X, Palette, Check, ShieldCheck } from 'lucide-react';
import { AppContext, useApp, api, send, useData, money, Badge, Loading, ErrorBox, Empty, Pagination, type Item } from './shared';
import { AuthPage, ProfilePage } from './people';
import { CartPage, OrdersPage, OrderDetail } from './orders';
import { AddressPage } from './addresses';
import { Workspace } from './workspace';

export default function Marketplace(){
 const path=usePathname();const router=useRouter();const [session,setSession]=useState<any>(null);const [cart,setCart]=useState<string[]>([]);const [ready,setReady]=useState(false);const [toast,setToast]=useState('');const [menu,setMenu]=useState(false);
 const refreshSession=()=>api('session').then(setSession).catch(()=>setSession({user:null}));
 useEffect(()=>{refreshSession();try{const stored=JSON.parse(localStorage.getItem('sillapa-cart')||'[]');if(Array.isArray(stored))setCart(stored.filter(v=>typeof v==='string').slice(0,20));}catch{}setReady(true);},[]);
 useEffect(()=>{if(ready)localStorage.setItem('sillapa-cart',JSON.stringify(cart));},[cart,ready]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(t);}},[toast]);
 useEffect(()=>{setMenu(false);},[path]);
 const user=session?.user;const addToCart=(id:string)=>{setCart(c=>c.includes(id)?c:[...c,id]);setToast('เพิ่มผลงานในตะกร้าแล้ว');};
 const value={user,session,cart,setCart,addToCart,notify:setToast,refreshSession};
 const workspace=path.startsWith('/studio');
 return <AppContext.Provider value={value}><a className="skip" href="#main">ข้ามไปเนื้อหา</a><header className="header"><Link href="/" className="brand" aria-label="SILLAPA หน้าหลัก"><Asterisk size={36} strokeWidth={2.5}/><span>SILLAPA<span className="brand-thai">พื้นที่ของศิลปะ</span></span></Link><nav className={menu?'main-nav open':'main-nav'} aria-label="เมนูหลัก"><Link className={path==='/'?'active':''} href="/">สำรวจผลงาน</Link><Link className={path.startsWith('/artists')?'active':''} href="/artists">ศิลปินของเรา</Link>{user&&<Link className={path.startsWith('/orders')?'active':''} href="/orders">คำสั่งซื้อ</Link>}{['admin','staff'].includes(user?.role)&&<Link className={workspace?'active':''} href="/studio">จัดการร้าน</Link>}</nav><div className="header-actions"><Link className="cart-button" href="/cart" aria-label={`ตะกร้าสินค้า ${cart.length} ชิ้น`}><ShoppingBag size={21}/><span className="cart-count">{cart.length}</span></Link>{user?<><Link className="account" href="/profile"><span className="avatar small">{user.name.slice(0,1)}</span><span>{user.name.split(' ')[0]}</span></Link><button className="icon-button logout" aria-label="ออกจากระบบ" onClick={async()=>{await send('auth/logout',{});await refreshSession();router.push('/');}}><LogOut size={18}/></button></>:<Link href="/login" className="button dark compact">เข้าสู่ระบบ <ArrowUpRight size={15}/></Link>}<button className="icon-button mobile-menu" aria-label="เปิดเมนู" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 <main id="main" className={workspace?'workspace-main':'site-main'}>{path==='/'?<Gallery/>:path.startsWith('/artworks/')?<ArtworkDetail id={path.split('/')[2]}/>:path==='/artists'?<Artists/>:path.startsWith('/artists/')?<ArtistDetail id={path.split('/')[2]}/>:path==='/login'||path==='/register'?<AuthPage register={path==='/register'}/>:path==='/cart'?<CartPage/>:path==='/orders'?<OrdersPage/>:path.startsWith('/orders/')?<OrderDetail id={path.split('/')[2]}/>:path==='/addresses'?<AddressPage/>:path==='/profile'?<ProfilePage/>:workspace?<Workspace/>:path==='/credits'?<Credits/>:<Empty title="ไม่พบหน้านี้"><Link className="button" href="/">กลับสู่แกลเลอรี</Link></Empty>}</main>
 <footer className="footer"><div><Link className="footer-brand" href="/">SILLAPA< Asterisk size={22}/></Link><span>ทุกผลงาน มีเรื่องราวของตัวเอง</span></div><Link href="/credits">เครดิตภาพตัวอย่าง</Link><span>© {new Date().getFullYear()} Sillapa Art Marketplace</span></footer>{toast&&<div className="toast" role="status"><Check size={19}/>{toast}</div>}</AppContext.Provider>;
}

export function ArtCard({art,list=false}:{art:Item,list?:boolean}){return <Link href={`/artworks/${art.id}`} className={`art-card ${list?'list-card':''}`}><div className="art-image"><img src={art.image} alt={art.title} loading="lazy"/>{art.status!=='approved'&&<Badge status={art.status}/>}<span className="art-open"><ArrowUpRight size={20}/></span></div><div className="art-info"><div className="art-meta"><span>{art.category_name}</span><span>{Number(art.width)} × {Number(art.height)} ซม.</span></div><h3>{art.title}</h3><div className="art-bottom"><span className="artist-name">{art.artist_name}</span><strong>{money(art.price)}</strong></div></div></Link>;}
function Gallery({artist}:{artist?:string}){
 const [q,setQ]=useState('');const [search,setSearch]=useState('');const [category,setCategory]=useState('');const [artistFilter,setArtistFilter]=useState('');const [max,setMax]=useState('');const [status,setStatus]=useState('');const [sort,setSort]=useState('newest');const [page,setPage]=useState(1);const [list,setList]=useState(false);const [filters,setFilters]=useState(false);
 useEffect(()=>{const t=setTimeout(()=>{setSearch(q);setPage(1);},300);return()=>clearTimeout(t);},[q]);
 const categories=useData('categories');const artists=useData('artists');const params=new URLSearchParams({q:search,category,artist:artist||artistFilter,max,status,sort,page:String(page)});const {data,error}=useData(`artworks?${params}`);const reset=()=>{setQ('');setCategory('');setArtistFilter('');setMax('');setStatus('');setSort('newest');setPage(1);};
 return <>{!artist&&<section className="gallery-intro"><div><div className="eyebrow"><span className="tiny-line"/> A SPACE FOR ART & YOU</div><h1>Art, with a <em>story.</em></h1><p>ค้นพบผลงานที่ใช่ สนับสนุนศิลปินรุ่นใหม่<br className="mobile-break"/> และเติมเรื่องราวให้พื้นที่ของคุณ</p></div><div className="intro-note"><div className="outline-star"><Asterisk size={52} strokeWidth={1}/></div><p>จากความตั้งใจของศิลปิน<br/>สู่มุมโปรดของคุณ</p><Link href="/artists">พบกับศิลปิน <ArrowUpRight size={17}/></Link></div></section>}
 <section className="gallery-section"><div className="section-heading"><h2>{artist?'ผลงานของศิลปิน':'สำรวจผลงาน'}<span className="count">{data?.total??'—'}</span></h2><div className="view-buttons"><button className={!list?'selected':''} aria-label="มุมมองตาราง" onClick={()=>setList(false)}><LayoutGrid size={19}/></button><button className={list?'selected':''} aria-label="มุมมองรายการ" onClick={()=>setList(true)}><List size={20}/></button></div></div><div className="gallery-tools"><div className="category-tabs"><button onClick={()=>{setCategory('');setPage(1);}} className={!category?'selected':''}>ทั้งหมด</button>{categories.data?.items.map((c:Item)=><button key={c.id} onClick={()=>{setCategory(c.id);setPage(1);}} className={category===c.id?'selected':''}>{c.name}</button>)}</div><label className="sort-label">เรียงตาม <select aria-label="เรียงผลงาน" value={sort} onChange={e=>{setSort(e.target.value);setPage(1);}}><option value="newest">ใหม่ล่าสุด</option><option value="price_asc">ราคา: ต่ำไปสูง</option><option value="price_desc">ราคา: สูงไปต่ำ</option><option value="oldest">เก่าที่สุด</option></select></label></div>
 <button className="button filter-toggle" onClick={()=>setFilters(!filters)}><SlidersHorizontal size={17}/>ตัวกรอง</button><div className="gallery-layout"><aside className={`filters ${filters?'show':''}`}><div className="filter-heading"><strong><SlidersHorizontal size={17}/>ตัวกรอง</strong><button className="text-button" onClick={reset}>ล้างทั้งหมด</button></div><label className="field-label">ค้นหาผลงาน<div className="search-input"><Search size={17}/><input placeholder="ชื่อผลงานหรือศิลปิน" value={q} onChange={e=>setQ(e.target.value)}/></div></label>{!artist&&<label className="field-label">ศิลปิน<select value={artistFilter} onChange={e=>{setArtistFilter(e.target.value);setPage(1);}}><option value="">ศิลปินทั้งหมด</option>{artists.data?.items.map((a:Item)=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>}<label className="field-label">ช่วงราคา<select value={max} onChange={e=>{setMax(e.target.value);setPage(1);}}><option value="">ทุกช่วงราคา</option><option value="3000">ไม่เกิน ฿3,000</option><option value="5000">ไม่เกิน ฿5,000</option><option value="10000">ไม่เกิน ฿10,000</option></select></label><div className="filter-divider"/><label className="check-label"><input type="checkbox" checked={status==='approved'} onChange={e=>{setStatus(e.target.checked?'approved':'');setPage(1);}}/>เฉพาะที่พร้อมจำหน่าย</label><div className="artist-invite"><Palette size={25}/><h3>ให้ผลงานของคุณ<br/>ได้พบเจ้าของคนใหม่</h3><p>ร่วมเป็นส่วนหนึ่งของ<br/>ชุมชนศิลปิน SILLAPA</p><Link href="/register">เริ่มต้นเป็นศิลปิน <ArrowUpRight size={16}/></Link></div></aside><div className="gallery-results"><ErrorBox text={error}/>{!data&&!error?<Loading/>:data?.items.length===0?<Empty title="ไม่พบผลงานที่ค้นหา"><p>ลองเปลี่ยนคำค้นหาหรือล้างตัวกรอง</p><button className="button" onClick={reset}>ล้างตัวกรอง</button></Empty>:<div className={`art-grid ${list?'list-grid':''}`}>{data?.items.map((art:Item)=><ArtCard key={art.id} art={art} list={list}/>)}</div>}<Pagination data={data} page={page} onChange={setPage}/><p className="sample-note">ภาพตัวอย่างเป็นศิลปะสาธารณสมบัติ ชื่อศิลปินนักศึกษาและราคาเป็นข้อมูลสาธิต <Link href="/credits">ดูเครดิตภาพ</Link></p></div></div></section></>;
}
function ArtworkDetail({id}:{id:string}){const {data,error}=useData(`artworks/${id}`);const {addToCart,cart,user}=useApp();if(error)return <ErrorBox text={error}/>;if(!data)return <Loading/>;const a=data.artwork;return <><div className="breadcrumb"><Link href="/">สำรวจผลงาน</Link><span>/</span><span>{a.title}</span></div><section className="detail-layout"><div className="detail-image"><img src={a.image} alt={a.title}/></div><div className="detail-info"><div className="eyebrow">{a.category_name}</div><h1>{a.title}</h1><Link className="artist-link" href={`/artists/${a.artist_id}`}><span className="avatar">{a.artist_name.slice(0,1)}</span><div><strong>{a.artist_name}</strong><small>{a.university||'ศิลปิน SILLAPA'}</small></div><ArrowUpRight size={19}/></Link><p className="detail-price">{money(a.price)}</p><Badge status={a.status}/><p className="description">{a.description}</p><dl className="specs"><div><dt>เทคนิค</dt><dd>{a.technique}</dd></div><div><dt>ขนาด</dt><dd>{Number(a.width)} × {Number(a.height)} ซม.</dd></div><div><dt>รูปแบบ</dt><dd>ผลงานต้นฉบับ · 1 ชิ้น</dd></div></dl><button className="button primary full" disabled={a.status!=='approved'||a.artist_id===user?.id||cart.includes(id)} onClick={()=>addToCart(id)}><ShoppingBag size={19}/>{cart.includes(id)?'อยู่ในตะกร้าแล้ว':a.status==='approved'?'เพิ่มลงตะกร้า':a.status==='reserved'?'ผลงานนี้ถูกจองแล้ว':'ยังไม่พร้อมจำหน่าย'}</button>{cart.includes(id)&&<Link className="button full" href="/cart">ไปที่ตะกร้า <ArrowRight size={17}/></Link>}<p className="trust-note"><ShieldCheck size={17}/>ผ่านการอนุมัติก่อนเผยแพร่ · ตรวจสอบการชำระเงินโดยแอดมิน</p>{a.credit&&<p className="sample-note">{a.credit} <Link href="/credits">เครดิตภาพ</Link></p>}</div></section></>;}
function Artists(){const {data,error}=useData('artists');return <><div className="page-heading"><span className="eyebrow">MEET THE MAKERS</span><h1>เรื่องราวเบื้องหลังฝีแปรง</h1><p>รู้จักศิลปินและค้นพบมุมมองใหม่ผ่านผลงานของพวกเขา</p></div><ErrorBox text={error}/>{!data&&!error?<Loading/>:<div className="artist-grid">{data?.items.map((a:Item)=><Link className="artist-card" href={`/artists/${a.id}`} key={a.id}>{a.image?<img src={a.image} alt={`ผลงานของ ${a.name}`}/>:<div className="artist-placeholder"><Palette size={60}/></div>}<div><span className="avatar">{a.name.slice(0,1)}</span><h2>{a.name}</h2><p>{a.university}</p><p>{a.bio}</p><strong>{a.count} ผลงาน <ArrowUpRight size={17}/></strong></div></Link>)}</div>}</>;}
function ArtistDetail({id}:{id:string}){const {data,error}=useData(`artists/${id}`);if(error)return <ErrorBox text={error}/>;if(!data)return <Loading/>;const a=data.artist;return <><section className="artist-profile"><span className="avatar large">{a.name.slice(0,1)}</span><div><span className="eyebrow">SILLAPA ARTIST</span><h1>{a.name}</h1><p>{a.university}</p><p>{a.bio||'ศิลปินคนนี้ยังไม่ได้เพิ่มประวัติ'}</p></div></section><Gallery artist={id}/></>;}
function Credits(){const [items,setItems]=useState<Item[]>([]);useEffect(()=>{fetch('/art/attributions.json').then(r=>r.json()).then(setItems);},[]);return <div className="narrow"><div className="page-heading"><span className="eyebrow">IMAGE CREDITS</span><h1>เครดิตภาพตัวอย่าง</h1><p>ภาพสาธารณสมบัติใช้เพื่อสาธิตระบบเท่านั้น ไม่ใช่ผลงานของนักศึกษาที่แสดงในโปรไฟล์ ชื่อรายการ ราคา และขนาดเป็นข้อมูลสมมติ</p></div>{items.map(a=><div className="credit-row" key={a.id}><img src={`/art/${a.filename}`} alt={a.title}/><div><h3>{a.title}</h3><p>{a.artist} · {a.license}</p><a href={a.source_url} target="_blank" rel="noreferrer">ดูต้นฉบับและสิทธิ์การใช้งาน ↗</a></div></div>)}</div>;}
