'use client';
import { useEffect, useState } from 'react';
import dynamic from 'next/dynamic';
import artVariants from '../public/art/variants.json';
import Link from 'next/link';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { Asterisk, ShoppingBag, ArrowUpRight, ArrowRight, Search, SlidersHorizontal, LayoutGrid, List, LogOut, Menu, X, Palette, ShieldCheck, Store } from 'lucide-react';
import { useApp, useData, money, Badge, Loading, ErrorBox, Empty, Pagination, type Item } from './shared';
const AuthPage=dynamic(()=>import('./people').then(m=>m.AuthPage),{loading:()=> <Loading/>});
const ProfilePage=dynamic(()=>import('./people').then(m=>m.ProfilePage),{loading:()=> <Loading/>});
const PublicProfile=dynamic(()=>import('./people').then(m=>m.PublicProfile),{loading:()=> <Loading/>});
import { CartPage, OrdersPage, OrderDetail } from './orders';
import { AddressPage } from './addresses';
const AdminPortal=dynamic(()=>import('./workspace').then(m=>m.AdminPortal),{loading:()=> <Loading/>});
const Workspace=dynamic(()=>import('./workspace').then(m=>m.Workspace),{loading:()=> <Loading/>});

export default function Marketplace(){
 const path=usePathname();const router=useRouter();const navigationParams=useSearchParams();const {user,session,sessionError,cart,logout}=useApp();const [menu,setMenu]=useState(false);const [logoutError,setLogoutError]=useState('');
 useEffect(()=>{setMenu(false);setLogoutError('');},[path,navigationParams]);
 useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setMenu(false);};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close);},[]);
 const signOut=async()=>{try{await logout();router.push('/');}catch(e:any){setLogoutError(e.message);}};
 const adminPath=path.startsWith('/admin');const workspace=path.startsWith('/studio');
 if(adminPath)return <><AdminPortal/></>;
 if(workspace)return <><div className="studio-app"><a className="skip" href="#main">ข้ามไปเนื้อหา</a><header className="studio-topbar"><Link href="/studio" className="studio-topbar-brand"><span>S</span><b>SILLAPA</b><strong>STUDIO</strong></Link><div className="studio-topbar-actions"><Link href="/"><Store size={17}/>เปิดหน้าร้าน</Link><Link href="/orders" aria-label="คำสั่งซื้อของฉัน"><ShoppingBag size={17}/><span>คำสั่งซื้อของฉัน</span></Link>{user&&<Link href="/profile" className="studio-topbar-user"><span className="avatar small">{user.name.slice(0,1)}</span>{user.name.split(' ')[0]}</Link>}{user&&<button className="icon-button" aria-label="ออกจากระบบ" onClick={signOut}><LogOut size={18}/></button>}</div></header><ErrorBox text={logoutError||sessionError}/><main id="main" className="workspace-main"><Workspace/></main></div></>;
 return <><a className="skip" href="#main">ข้ามไปเนื้อหา</a><div className="utility-bar"><span>พื้นที่ของศิลปะ สำหรับทุกคน</span><div><Link href="/artists">ร่วมเป็นศิลปิน</Link><Link href="/orders">ติดตามคำสั่งซื้อ</Link></div></div><header className="header"><Link href="/" className="brand" aria-label="SILLAPA หน้าหลัก"><Asterisk size={32} strokeWidth={2.8}/><span>SILLAPA</span></Link><nav className={menu?'main-nav open':'main-nav'} id="store-navigation" aria-label="เมนูหลัก"><Link className={path==='/'&&!navigationParams.get('category')?'active':''} href="/">มาใหม่</Link><Link className={path==='/gallery'?'active':''} href="/gallery">งานศิลปะ</Link><Link className={path.startsWith('/artists')?'active':''} href="/artists">ศิลปิน</Link><Link className={path.startsWith('/orders')?'active':''} href="/orders">คำสั่งซื้อ</Link><div className="mobile-account-menu">{user?.role==='admin'&&<Link href="/admin">Admin Portal</Link>}{user?.role==='staff'&&<Link href="/studio">พื้นที่ศิลปิน</Link>}{user?<><Link href="/profile">โปรไฟล์ของฉัน</Link><Link href="/addresses">ที่อยู่ของฉัน</Link><button onClick={signOut}>ออกจากระบบ</button></>:session?<><Link href="/login">เข้าสู่ระบบ</Link><Link href="/register">สมัครสมาชิก</Link></>:<span>กำลังตรวจสอบบัญชี…</span>}</div></nav><div className="header-actions">{user&&['admin','staff'].includes(user.role)&&<Link className="header-portal" href={user.role==='admin'?'/admin':'/studio'} aria-label={user.role==='admin'?'Admin Portal':'พื้นที่ศิลปิน'}><Store size={18}/><span>{user.role==='admin'?'Admin Portal':'พื้นที่ศิลปิน'}</span></Link>}<Link className="header-search" aria-label="ค้นหาผลงาน" href="/gallery#discover"><Search size={18}/><span>ค้นหาผลงาน</span></Link><Link className="cart-button" href="/cart" aria-label={`ตะกร้าสินค้า ${cart.length} ชิ้น`}><ShoppingBag size={22}/><span className="cart-count">{cart.length}</span></Link>{user?<><Link className="account" href="/profile"><span className="avatar small">{user.name.slice(0,1)}</span><span>{user.name.split(' ')[0]}</span></Link><button className="icon-button logout" aria-label="ออกจากระบบ" onClick={signOut}><LogOut size={18}/></button></>:<Link href="/login" className="account-link">เข้าสู่ระบบ</Link>}<button className="icon-button mobile-menu" aria-label={menu?'ปิดเมนู':'เปิดเมนู'} aria-expanded={menu} aria-controls="store-navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header><div className="promo-strip"><strong>ค้นพบงานศิลป์ชิ้นพิเศษ</strong><span>จัดส่งฟรีทั่วประเทศ · ทุกผลงานผ่านการอนุมัติ</span></div>
 <ErrorBox text={logoutError||sessionError}/><main id="main" className={workspace?'workspace-main':'site-main'}>{path==='/'||path==='/gallery'?<Gallery/>:path.startsWith('/artworks/')?<ArtworkDetail id={path.split('/')[2]}/>:path==='/artists'?<Artists/>:path.startsWith('/artists/')?<ArtistDetail id={path.split('/')[2]}/>:path==='/login'||path==='/register'?<AuthPage key={path} register={path==='/register'}/>:path==='/cart'?<CartPage/>:path==='/orders'?<OrdersPage/>:path.startsWith('/orders/')?<OrderDetail id={path.split('/')[2]}/>:path==='/addresses'?<AddressPage/>:path.startsWith('/profiles/')?<PublicProfile id={path.split('/')[2]}/>:path==='/profile'?<ProfilePage/>:workspace?<Workspace/>:path==='/credits'?<Credits/>:<Empty title="ไม่พบหน้านี้"><Link className="button" href="/">กลับสู่แกลเลอรี</Link></Empty>}</main>
 <footer className="footer"><div><Link className="footer-brand" href="/">SILLAPA< Asterisk size={22}/></Link><span>ทุกผลงาน มีเรื่องราวของตัวเอง</span></div><Link href="/credits">เครดิตภาพตัวอย่าง</Link><span>© {new Date().getFullYear()} Sillapa Art Marketplace</span></footer></>;
}

export function ArtCard({art,list=false}:{art:Item,list?:boolean}){const variant=(artVariants as Record<string,{small:string,large:string}>)[art.image];return <Link href={`/artworks/${art.id}`} className={`art-card ${list?'list-card':''}`}><div className="art-image"><img src={variant?.small||art.image} srcSet={variant?`${variant.small} 480w, ${variant.large} 960w`:undefined} sizes="(max-width:600px) 46vw, (max-width:1000px) 30vw, 23vw" alt={art.title} loading="lazy" decoding="async"/>{art.status!=='approved'&&<Badge status={art.status}/>}<span className="art-open"><ArrowUpRight size={20}/></span></div><div className="art-info"><div className="art-meta"><span>{art.category_name}</span><span>{Number(art.width)} × {Number(art.height)} ซม.</span></div><h3>{art.title}</h3><div className="art-bottom"><span className="artist-name">{art.artist_name}</span><strong>{money(art.price)}</strong></div></div></Link>;}
const normalizeCategory=(value:string|null)=>['illustration','landscape','portrait','still-life'].includes(value||'')?'painting':value||'';
function Gallery({artist}:{artist?:string}){
 const urlParams=useSearchParams();const router=useRouter();const path=usePathname();const GalleryHeading=path==='/gallery'?'h1':'h2';
 const update=(values:Record<string,string>,replace=false)=>{const next=new URLSearchParams(urlParams.toString());for(const [key,value] of Object.entries(values)){if(value)next.set(key,value);else next.delete(key);}const target=`${path}${next.size?'?'+next.toString():''}`;if(replace)window.history.replaceState(null,'',target);else window.history.pushState(null,'',target);};
 const category=normalizeCategory(urlParams.get('category'));const artistFilter=urlParams.get('artist')||'';const max=urlParams.get('max')||'';const status=urlParams.get('status')||'';const sort=urlParams.get('sort')||'newest';const page=Math.max(1,Number(urlParams.get('page'))||1);const list=urlParams.get('view')==='list';const filters=urlParams.get('filters')==='1';
 const [q,setQ]=useState(urlParams.get('q')||'');const search=urlParams.get('q')||'';
 useEffect(()=>{setQ(urlParams.get('q')||'');},[search]);
 useEffect(()=>{if(q===search)return;const timer=setTimeout(()=>update({q:q.trim(),page:''},true),200);return()=>clearTimeout(timer);},[q,search]);
 const selectCategory=(value:string)=>update({category:value,page:''});const setArtistFilter=(value:string)=>update({artist:value,page:''});const setMax=(value:string)=>update({max:value,page:''});const setStatus=(value:string)=>update({status:value,page:''});const setSort=(value:string)=>update({sort:value==='newest'?'':value,page:''});const setPage=(value:number)=>update({page:value===1?'':String(value)});const setList=(value:boolean)=>update({view:value?'list':''});const setFilters=(value:boolean)=>update({filters:value?'1':''});
 const poster=useData('site_settings');const categories=useData('categories');const artists=useData('artists');const params=new URLSearchParams({q:search,category,artist:artist||artistFilter,max,status,sort,page:String(page)});const {data,error}=useData(`artworks?${params}`);const reset=()=>{setQ('');router.push(path,{scroll:false});};
 return <>{path==='/'&&!artist&&!category&&<><section className="gallery-intro"><img src={poster.data?.image||"/art/art-1.jpg"} alt="โปสเตอร์ผลงานเด่นประจำสัปดาห์" fetchPriority="high" decoding="async"/><div className="hero-copy"><span className="hero-kicker">MEME OF THE WEEK</span><h1>มีมที่<br/>พูดแทนคุณ</h1><p>ค้นพบงานสนุกจากศิลปินรุ่นใหม่<br/>เอาไว้เติมรอยยิ้มให้พื้นที่ของคุณ</p><a className="hero-cta" href="#discover">เลือกชมผลงาน <ArrowRight size={18}/></a></div></section><div className="shop-categories" aria-label="เลือกดูตามหมวด"><a href="#discover">มาใหม่</a><Link href="/gallery#discover">งานศิลปะทั้งหมด</Link><Link href="/artists">ศิลปินน่าจับตา</Link></div></>}
 <section className="gallery-section" id="discover"><div className="section-heading"><div><span className="section-kicker">CURATED FOR YOU</span><GalleryHeading className="gallery-title">{artist?'ผลงานของศิลปิน':category?(categories.data?.items.find((c:Item)=>c.id===category)?.name||'ผลงานในหมวดนี้'):'ผลงานเด่น'}<span className="count">{data?.total??'—'}</span></GalleryHeading></div><div className="view-buttons"><button className={!list?'selected':''} aria-label="มุมมองตาราง" onClick={()=>setList(false)}><LayoutGrid size={19}/></button><button className={list?'selected':''} aria-label="มุมมองรายการ" onClick={()=>setList(true)}><List size={20}/></button></div></div><label className="field-label gallery-search">ค้นหาผลงาน<div className="search-input"><Search size={17}/><input type="search" placeholder="ชื่อผลงานหรือศิลปิน" value={q} onChange={e=>setQ(e.target.value)}/></div></label><div className="gallery-tools">{categories.data?.items.length>1&&<div className="category-tabs"><button onClick={()=>selectCategory('')} className={!category?'selected':''}>ทั้งหมด</button>{categories.data?.items.map((c:Item)=><button key={c.id} onClick={()=>selectCategory(c.id)} className={category===c.id?'selected':''}>{c.name}</button>)}</div>}<div className="tool-actions"><button className="filter-inline" aria-expanded={filters} aria-controls="gallery-filters" onClick={()=>setFilters(!filters)}><SlidersHorizontal size={16}/> ตัวกรอง</button><label className="sort-label"><select aria-label="เรียงผลงาน" value={sort} onChange={e=>{setSort(e.target.value);}}><option value="newest">ใหม่ล่าสุด</option><option value="price_asc">ราคา: ต่ำไปสูง</option><option value="price_desc">ราคา: สูงไปต่ำ</option><option value="oldest">เก่าที่สุด</option></select></label></div></div>
 <button className="button filter-toggle" onClick={()=>setFilters(!filters)}><SlidersHorizontal size={17}/>ตัวกรอง</button><div className="gallery-layout"><aside id="gallery-filters" className={`filters ${filters?'show':''}`}><div className="filter-heading"><strong><SlidersHorizontal size={17}/>ตัวกรอง</strong><button className="text-button" onClick={reset}>ล้างทั้งหมด</button></div>{!artist&&<label className="field-label">ศิลปิน<select value={artistFilter} onChange={e=>{setArtistFilter(e.target.value);}}><option value="">ศิลปินทั้งหมด</option>{artists.data?.items.map((a:Item)=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>}<label className="field-label">ช่วงราคา<select value={max} onChange={e=>{setMax(e.target.value);}}><option value="">ทุกช่วงราคา</option><option value="3000">ไม่เกิน ฿3,000</option><option value="5000">ไม่เกิน ฿5,000</option><option value="10000">ไม่เกิน ฿10,000</option></select></label><div className="filter-divider"/><label className="check-label"><input type="checkbox" checked={status==='approved'} onChange={e=>{setStatus(e.target.checked?'approved':'');}}/>เฉพาะที่พร้อมจำหน่าย</label><div className="artist-invite"><Palette size={25}/><h3>ให้ผลงานของคุณ<br/>ได้พบเจ้าของคนใหม่</h3><p>ร่วมเป็นส่วนหนึ่งของ<br/>ชุมชนศิลปิน SILLAPA</p><Link href="/register">เริ่มต้นเป็นศิลปิน <ArrowUpRight size={16}/></Link></div></aside><div className="gallery-results"><ErrorBox text={error}/>{!data&&!error?<Loading variant="gallery"/>:data?.items.length===0?<Empty title="ไม่พบผลงานที่ค้นหา"><p>ลองเปลี่ยนคำค้นหาหรือล้างตัวกรอง</p><button className="button" onClick={reset}>ล้างตัวกรอง</button></Empty>:<div className={`art-grid ${list?'list-grid':''}`}>{data?.items.map((art:Item)=><ArtCard key={art.id} art={art} list={list}/>)}</div>}<Pagination data={data} page={page} onChange={setPage}/><p className="sample-note">ภาพมีมชุดนี้มาจาก Wikimedia Commons และใช้สำหรับสาธิตระบบ ชื่อศิลปินในร้านและราคาเป็นข้อมูลสมมติ <Link href="/credits">ดูรายละเอียดภาพ</Link></p></div></div></section></>;
}
function ArtworkDetail({id}:{id:string}){const {data,error}=useData(`artworks/${id}`);const {addToCart,cart,user}=useApp();if(error)return <ErrorBox text={error}/>;if(!data)return <Loading/>;const a=data.artwork;return <><div className="breadcrumb"><Link href="/">สำรวจผลงาน</Link><span>/</span><span>{a.title}</span></div><section className="detail-layout"><div className="detail-image"><img src={a.image} alt={a.title}/></div><div className="detail-info"><div className="eyebrow">{a.category_name}</div><h1>{a.title}</h1><Link className="artist-link" href={`/artists/${a.artist_id}`}><span className="avatar">{a.artist_name.slice(0,1)}</span><div><strong>{a.artist_name}</strong><small>{a.university||'ศิลปิน SILLAPA'}</small></div><ArrowUpRight size={19}/></Link><p className="detail-price">{money(a.price)}</p><Badge status={a.status}/><p className="description">{a.description}</p><dl className="specs"><div><dt>เทคนิค</dt><dd>{a.technique}</dd></div><div><dt>ขนาด</dt><dd>{Number(a.width)} × {Number(a.height)} ซม.</dd></div><div><dt>รูปแบบ</dt><dd>ผลงานต้นฉบับ · 1 ชิ้น</dd></div></dl><button className="button primary full" disabled={a.status!=='approved'||a.artist_id===user?.id||cart.includes(id)} onClick={()=>addToCart(id)}><ShoppingBag size={19}/>{cart.includes(id)?'อยู่ในตะกร้าแล้ว':a.status==='approved'?'เพิ่มลงตะกร้า':a.status==='reserved'?'ผลงานนี้ถูกจองแล้ว':'ยังไม่พร้อมจำหน่าย'}</button>{cart.includes(id)&&<Link className="button full" href="/cart">ไปที่ตะกร้า <ArrowRight size={17}/></Link>}<p className="trust-note"><ShieldCheck size={17}/>ผ่านการอนุมัติก่อนเผยแพร่ · ตรวจสอบการชำระเงินโดยแอดมิน</p>{a.credit&&<p className="sample-note">{a.credit} <Link href="/credits">เครดิตภาพ</Link></p>}</div></section></>;}
function Artists(){const {data,error}=useData('artists');return <><div className="page-heading"><span className="eyebrow">MEET THE MAKERS</span><h1>เรื่องราวเบื้องหลังฝีแปรง</h1><p>รู้จักศิลปินและค้นพบมุมมองใหม่ผ่านผลงานของพวกเขา</p></div><ErrorBox text={error}/>{!data&&!error?<Loading/>:data?.items.length===0?<Empty title="ยังไม่มีศิลปิน"><Link className="button" href="/gallery">เลือกดูผลงาน</Link></Empty>:<div className="artist-grid">{data?.items.map((a:Item)=><Link className="artist-card" href={`/artists/${a.id}`} key={a.id}>{a.image?<img src={a.image} alt={`ผลงานของ ${a.name}`}/>:<div className="artist-placeholder"><Palette size={60}/></div>}<div><span className="avatar">{a.name.slice(0,1)}</span><h2>{a.name}</h2><p>{a.university}</p><p>{a.bio}</p><strong>{a.count} ผลงาน <ArrowUpRight size={17}/></strong></div></Link>)}</div>}</>;}
function ArtistDetail({id}:{id:string}){const {data,error}=useData(`artists/${id}`);if(error)return <ErrorBox text={error}/>;if(!data)return <Loading/>;const a=data.artist;return <><section className="artist-profile"><span className="avatar large">{a.name.slice(0,1)}</span><div><span className="eyebrow">SILLAPA ARTIST</span><h1>{a.name}</h1><p>{a.university}</p><p>{a.bio||'ศิลปินคนนี้ยังไม่ได้เพิ่มประวัติ'}</p><Link className="button" href={`/profiles/${id}`}>ดูโปรไฟล์</Link></div></section><Gallery artist={id}/></>;}
function Credits(){const [items,setItems]=useState<Item[]|null>(null);const [error,setError]=useState('');useEffect(()=>{let live=true;fetch('/art/attributions.json').then(r=>{if(!r.ok)throw new Error('โหลดรายละเอียดภาพไม่สำเร็จ');return r.json();}).then(data=>{if(live)setItems(data);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);return <div className="narrow"><div className="page-heading"><span className="eyebrow">IMAGE DETAILS</span><h1>รายละเอียดภาพตัวอย่าง</h1><p>ภาพมีมทั้งหมดนำมาจากอินเทอร์เน็ตผ่าน Wikimedia Commons ตามสัญญาอนุญาตของแต่ละภาพ ไม่ใช่ผลงานจริงของนักศึกษาที่แสดงในโปรไฟล์ ชื่อรายการ ราคา และขนาดเป็นข้อมูลสมมติ</p></div><ErrorBox text={error}/>{!items&&!error&&<Loading/>}{items?.map(a=><div className="credit-row" key={a.id}><img src={`/art/${a.filename}`} alt={a.title}/><div><h3>{a.title}</h3><p>{a.artist} · {a.license}</p><a href={a.source_url} target="_blank" rel="noreferrer">ดูภาพต้นฉบับและสัญญาอนุญาต ↗</a></div></div>)}</div>;}
