'use client';
import { useEffect, useState, type FormEvent } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowRight, Asterisk, Check, UserRound } from 'lucide-react';
import { useApp, send, ErrorBox, Loading, Upload, useData } from './shared';
export function AuthPage({register}:{register:boolean}) {
 const {session,refreshSession}=useApp();
 const router=useRouter();
 const [email,setEmail]=useState('');
 const [password,setPassword]=useState('');
 const [name,setName]=useState('');
 const [artist,setArtist]=useState(false);
 const [busy,setBusy]=useState(false);
 const [error,setError]=useState('');
 const [fieldErrors,setFieldErrors]=useState<Record<string,string>>({});
 useEffect(()=>{const reason=new URLSearchParams(location.search).get('google_error');if(reason)setError(reason);},[]);
 const clearField=(field:string)=>setFieldErrors(current=>({...current,[field]:''}));
 const submit=async(e:FormEvent<HTMLFormElement>)=>{
  e.preventDefault();
  const next:Record<string,string>={};
  if(register&&name.trim().length<2)next.name='กรุณากรอกชื่ออย่างน้อย 2 ตัวอักษร';
  if(!email.trim())next.email='กรุณากรอกอีเมล';
  else if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim()))next.email='รูปแบบอีเมลไม่ถูกต้อง';
  if(!password)next.password='กรุณากรอกรหัสผ่าน';
  else if(register&&password.length<10)next.password='รหัสผ่านต้องมีอย่างน้อย 10 ตัวอักษร';
  setFieldErrors(next);setError('');
  if(Object.keys(next).length)return;
  setBusy(true);
  try{await send(`auth/${register?'register':'login'}`,{email,password,name,artist_requested:artist});await refreshSession();router.push('/');}
  catch(e:any){setError(e.message);}
  finally{setBusy(false);}
 };
 return <div className="auth-layout"><div className="auth-art"><img src="/art/art-1.jpg" alt="แมวมีมจากอินเทอร์เน็ต — ภาพตัวอย่างจาก Wikimedia Commons"/><div><Asterisk size={48}/><h2>Good art.<br/>Great connections.</h2><p>ให้ศิลปะเชื่อมต่อคุณกับเรื่องราวใหม่</p></div></div><div className="auth-form"><span className="eyebrow">WELCOME TO SILLAPA</span><h1>{register?'เริ่มต้นเรื่องราวของคุณ':'ยินดีต้อนรับกลับ'}</h1><p>{register?'สมัครสมาชิกเพื่อสะสมงานศิลป์หรือแบ่งปันผลงานของคุณ':'เข้าสู่ระบบเพื่อพบกับผลงานชิ้นโปรดของคุณ'}</p>{session?.googleConfigured?<a className="google-button" href="/api/auth/google"><GoogleMark/>{register?'สมัครสมาชิกด้วย Google':'เข้าสู่ระบบด้วย Google'}</a>:<div className="google-disabled"><GoogleMark/><span>Google Login ยังไม่ได้ตั้งค่า</span></div>}<div className="auth-divider"><span>หรือใช้อีเมล</span></div><form noValidate onSubmit={submit}>{register&&<label className="field-label">ชื่อที่แสดง<input aria-invalid={!!fieldErrors.name} maxLength={100} autoComplete="name" value={name} onChange={e=>{setName(e.target.value);clearField('name');}}/>{fieldErrors.name&&<span className="field-error" role="alert">{fieldErrors.name}</span>}</label>}<label className="field-label">อีเมล<input aria-invalid={!!fieldErrors.email} type="email" autoComplete="email" value={email} onChange={e=>{setEmail(e.target.value);clearField('email');}}/>{fieldErrors.email&&<span className="field-error" role="alert">{fieldErrors.email}</span>}</label><label className="field-label">รหัสผ่าน<input aria-invalid={!!fieldErrors.password} type="password" maxLength={128} autoComplete={register?'new-password':'current-password'} value={password} onChange={e=>{setPassword(e.target.value);clearField('password');}}/>{register&&!fieldErrors.password&&<small>อย่างน้อย 10 ตัวอักษร</small>}{fieldErrors.password&&<span className="field-error" role="alert">{fieldErrors.password}</span>}</label>{register&&<label className="check-label"><input type="checkbox" checked={artist} onChange={e=>setArtist(e.target.checked)}/>ต้องการเป็นศิลปิน (รอแอดมินอนุมัติสิทธิ์)</label>}<ErrorBox text={error}/><button className="button primary full" disabled={busy}>{busy?'กำลังดำเนินการ…':register?'สร้างบัญชี':'เข้าสู่ระบบ'}<ArrowRight size={18}/></button></form><p className="auth-switch">{register?'มีบัญชีอยู่แล้ว?':'ยังไม่มีบัญชี?'} <Link href={register?'/login':'/register'}>{register?'เข้าสู่ระบบ':'สมัครสมาชิก'}</Link></p>{session?.demo&&<div className="demo-box"><strong>บัญชีทดลองในเครื่อง</strong><p>รหัสผ่านทุกบัญชี: <code>ArtDemo2026!</code></p><div>{[['customer','ลูกค้า'],['artist','ศิลปิน'],['admin','แอดมิน']].map(([role,label])=><button key={role} type="button" onClick={()=>{setEmail(`${role}@demo.local`);setPassword('ArtDemo2026!');setFieldErrors({});setError('');}}>{label}</button>)}</div></div>}</div></div>;
}
function GoogleMark(){return <svg aria-hidden="true" viewBox="0 0 24 24" width="20" height="20"><path fill="#4285F4" d="M21.6 12.2c0-.7-.1-1.4-.2-2H12v3.9h5.4a4.7 4.7 0 0 1-2 3v2.5h3.3c1.9-1.8 2.9-4.4 2.9-7.4"/><path fill="#34A853" d="M12 22c2.7 0 5-.9 6.7-2.4l-3.3-2.5c-.9.6-2.1 1-3.4 1a5.9 5.9 0 0 1-5.5-4.1H3.1v2.6A10 10 0 0 0 12 22"/><path fill="#FBBC05" d="M6.5 14a6 6 0 0 1 0-3.9V7.4H3.1a10 10 0 0 0 0 9.2z"/><path fill="#EA4335" d="M12 6a5.4 5.4 0 0 1 3.8 1.5l2.9-2.9A9.7 9.7 0 0 0 3.1 7.4l3.4 2.7A5.9 5.9 0 0 1 12 6"/></svg>}
export function PublicProfile({id}:{id:string}){const {data,error}=useData(`profile/${id}`);const {user}=useApp();if(error)return <ErrorBox text={error}/>;if(!data)return <Loading/>;const p=data.profile;return <div className="narrow"><ProfileHeader profile={p}/><div className="panel stack"><p className="preserve-lines">{p.bio||'ยังไม่ได้เพิ่มคำแนะนำตัว'}</p><p>{p.university}</p>{['staff','admin'].includes(p.role)&&<Link className="button" href={`/artists/${p.id}`}>ดูผลงานของศิลปิน</Link>}{user?.id===p.id&&<Link className="button primary" href="/profile">ปรับแต่งโปรไฟล์</Link>}</div></div>;}
function ProfileHeader({profile:p}:{profile:any}){return <section className="profile-header" style={{borderColor:p.accent||'#3151e8'}}><div className="profile-cover" style={{background:p.accent||'#3151e8'}}>{p.cover&&<img src={p.cover} alt="รูปปกโปรไฟล์"/>}</div><div className="profile-identity"><span className="profile-avatar">{p.avatar?<img src={p.avatar} alt="รูปโปรไฟล์"/>:p.name?.slice(0,1)}</span><div><h1>{p.name}</h1><p>{{admin:'ผู้ดูแลระบบ',staff:'ศิลปิน',customer:'ลูกค้า'}[p.role as string]}</p></div></div></section>;}
export function ProfilePage(){const {user,session,refreshSession,notify}=useApp();const [error,setError]=useState('');const [busy,setBusy]=useState(false);if(!session)return <Loading/>;if(!user)return <div className="empty"><h2>กรุณาเข้าสู่ระบบก่อน</h2><Link className="button primary" href="/login">เข้าสู่ระบบ</Link></div>;return <ProfileEditor key={user.id} user={user} refreshSession={refreshSession} notify={notify} error={error} setError={setError} busy={busy} setBusy={setBusy}/>;}
function ProfileEditor({user,refreshSession,notify,error,setError,busy,setBusy}:any){const [avatar,setAvatar]=useState(user.avatar||'');const [cover,setCover]=useState(user.cover||'');const [accent,setAccent]=useState(user.accent||'#3151e8');return <div className="narrow"><ProfileHeader profile={{...user,avatar,cover,accent}}/><div className="profile-actions"><Link className="button" href={`/profiles/${user.id}`}>ดูโปรไฟล์ของฉัน</Link><Link className="button" href="/addresses">ที่อยู่ของฉัน</Link></div><form noValidate className="panel form-grid" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{await send('profile',{name:f.get('name'),bio:f.get('bio'),university:f.get('university'),artist_requested:f.get('artist_requested')==='on',avatar,cover,accent},'PATCH');await refreshSession();notify('บันทึกโปรไฟล์แล้ว');}catch(e:any){setError(e.message);}finally{setBusy(false);}}}><div><h3>รูปโปรไฟล์</h3><Upload kind="profile" onUploaded={d=>setAvatar(d.url)}/>{avatar&&<button type="button" className="text-button" onClick={()=>setAvatar('')}>ลบรูปโปรไฟล์</button>}</div><div><h3>รูปปก</h3><Upload kind="profile" onUploaded={d=>setCover(d.url)}/>{cover&&<button type="button" className="text-button" onClick={()=>setCover('')}>ลบรูปปก</button>}</div><label className="field-label">ชื่อที่แสดง<input name="name" defaultValue={user.name} maxLength={100}/></label><label className="field-label">คณะ / มหาวิทยาลัย<input name="university" defaultValue={user.university} maxLength={150}/></label><label className="field-label">สีโปรไฟล์<input type="color" value={accent} onChange={e=>setAccent(e.target.value)}/></label><label className="field-label span-2">แนะนำตัว<textarea name="bio" rows={5} maxLength={1000} defaultValue={user.bio}/></label>{user.role==='customer'&&<label className="check-label span-2"><input name="artist_requested" type="checkbox" defaultChecked={user.artist_requested}/>ขอเปิดโปรไฟล์ศิลปิน (รอแอดมินอนุมัติ)</label>}<div className="span-2"><ErrorBox text={error}/><button className="button primary" disabled={busy}>{busy?'กำลังบันทึก…':'บันทึกโปรไฟล์'}</button></div></form></div>;}
