'use client';
import { createContext, useContext, useEffect, useState, useRef, type ReactNode } from 'react';
import { X, ChevronLeft, ChevronRight, LoaderCircle, CircleAlert, ImagePlus, Check } from 'lucide-react';
export type Item=Record<string,any>;
export const money=(n:number|string)=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',maximumFractionDigits:2}).format(Number(n)/100);
export const date=(d:string)=>new Date(d).toLocaleDateString('th-TH',{day:'numeric',month:'short',year:'numeric'});
export const statusNames:Item={approved:'พร้อมจำหน่าย',pending:'รออนุมัติ',rejected:'ต้องแก้ไข',reserved:'ถูกจองแล้ว',sold:'ขายแล้ว',pending_payment:'รอชำระเงิน',paid:'ชำระแล้ว',shipped:'จัดส่งแล้ว',completed:'สำเร็จ',cancelled:'ยกเลิก'};
export async function api(path:string,options?:RequestInit){const res=await fetch(`/api/${path}`,{...options,headers:options?.body instanceof FormData?options.headers:{'Content-Type':'application/json',...options?.headers}});const data=await res.json();if(!res.ok){const error=new Error(data.error||'เกิดข้อผิดพลาด') as Error&{status?:number};error.status=res.status;throw error;}return data;}
export const send=(path:string,data:any,method='POST')=>api(path,{method,body:JSON.stringify(data)});
export function useData(path:string){const [data,setData]=useState<any>(null);const [error,setError]=useState('');const [version,setVersion]=useState(0);useEffect(()=>{let live=true;let timer:ReturnType<typeof setTimeout>;setError('');setData(null);const load=(attempt=0)=>api(path).then(d=>{if(live)setData(d);}).catch((e:Error&{status?:number})=>{if(!live)return;if(attempt<2&&(!e.status||e.status>=500)){timer=setTimeout(()=>load(attempt+1),500*(attempt+1));return;}setError(e.message);});load();return()=>{live=false;clearTimeout(timer);};},[path,version]);return {data,error,reload:()=>setVersion(v=>v+1)};}
export const AppContext=createContext<any>(null);
export const useApp=()=>useContext(AppContext);
export function Badge({status}:{status:string}){return <span className={`badge ${status}`}>{statusNames[status]||status}</span>;}
export function Loading(){return <div className="loading" role="status"><LoaderCircle className="spin" size={22}/> กำลังโหลดข้อมูล…</div>;}
export function ErrorBox({text}:{text:string}){return text?<div className="error" role="alert"><CircleAlert size={18}/>{text}</div>:null;}
export function Empty({title='ยังไม่มีรายการ',children}:{title?:string,children?:ReactNode}){return <div className="empty"><div className="empty-symbol">✳</div><h3>{title}</h3>{children}</div>;}
export function Pagination({data,page,onChange}:{data:any,page:number,onChange:(page:number)=>void}){return data?.pages>1?<div className="pagination"><button className="icon-button" aria-label="หน้าก่อนหน้า" disabled={page<=1} onClick={()=>onChange(page-1)}><ChevronLeft size={18}/></button><span>หน้า {page} จาก {data.pages}</span><button className="icon-button" aria-label="หน้าถัดไป" disabled={page>=data.pages} onClick={()=>onChange(page+1)}><ChevronRight size={18}/></button></div>:null;}
export function Modal({title,children,onClose}:{title:string,children:ReactNode,onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();const dialog=ref.current;return()=>dialog?.close();},[]);return <dialog ref={ref} onCancel={onClose} aria-labelledby="dialog-title" onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal-head"><h2 id="dialog-title">{title}</h2><button className="icon-button" aria-label="ปิดหน้าต่าง" onClick={onClose}><X size={20}/></button></div>{children}</dialog>;}
export function Upload({kind,onUploaded}:{kind:'art'|'slip',onUploaded:(data:any)=>void}){const [busy,setBusy]=useState(false);const [error,setError]=useState('');return <div><label className={`upload ${busy?'disabled':''}`}><ImagePlus size={24}/><strong>{busy?'กำลังอัปโหลด…':kind==='art'?'เลือกภาพผลงาน':'เลือกภาพสลิปการชำระเงิน'}</strong><span>JPG, PNG หรือ WebP · ไม่เกิน 3 MB</span><input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');try{const form=new FormData();form.set('file',file);form.set('kind',kind);const data=await api('upload',{method:'POST',body:form});onUploaded(data);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}/></label><ErrorBox text={error}/></div>;}
