'use client';
import { createContext, useContext, useEffect, useState, useRef, useCallback, type ReactNode, type Dispatch, type SetStateAction } from 'react';
import { reportUX } from '@/lib/ux-metrics';
import { Suspense } from 'react';
import { usePathname, useSearchParams } from 'next/navigation';
import { X, ChevronLeft, ChevronRight, ImagePlus, Check } from 'lucide-react';
export type Item=Record<string,any>;
export const money=(n:number|string)=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',maximumFractionDigits:2}).format(Number(n)/100);
export const date=(d:string)=>new Date(d).toLocaleDateString('th-TH',{day:'numeric',month:'short',year:'numeric'});
export const statusNames:Item={approved:'พร้อมจำหน่าย',pending:'รออนุมัติ',rejected:'ต้องแก้ไข',reserved:'ถูกจองแล้ว',sold:'ขายแล้ว',pending_payment:'รอชำระเงิน',paid:'ชำระแล้ว',shipped:'จัดส่งแล้ว',completed:'สำเร็จ',cancelled:'ยกเลิก'};
export async function api(path:string,options?:RequestInit){const started=performance.now();const res=await fetch(`/api/${path}`,{...options,headers:options?.body instanceof FormData?options.headers:{'Content-Type':'application/json',...options?.headers}});const elapsed=performance.now()-started;if(elapsed>1500)reportUX('slow_api',Math.round(elapsed),path.split(/[/?]/)[0]);const raw=await res.text();let data:any={};try{data=raw?JSON.parse(raw):{};}catch{data={};}if(!res.ok){if(res.status>=500)reportUX('api_error',res.status,path.split(/[/?]/)[0]);const message=data.error||(res.status===413?'ไฟล์หรือข้อมูลมีขนาดใหญ่เกินไป กรุณาเลือกไฟล์ที่เล็กลง':res.status>=500?'ระบบไม่พร้อมใช้งานชั่วคราว กรุณาลองอีกครั้ง':'ดำเนินการไม่สำเร็จ กรุณาตรวจสอบข้อมูล');const error=new Error(message) as Error&{status?:number};error.status=res.status;throw error;}if(raw&&!Object.keys(data).length)throw new Error('ระบบตอบกลับไม่ถูกต้อง กรุณาลองอีกครั้ง');return data;}
export const send=async(path:string,data:any,method='POST')=>{const result=await api(path,{method,body:JSON.stringify(data)});clearPublicCache();return result;};
// Cache public lists only. Account, orders and management data always load afresh.
const PUBLIC_PREVIEW_KEY='sillapa-public-preview-v1';
const publicCache=new Map<string,{data:any,time:number,fresh?:boolean}>();
function restorePublicCache(){if(typeof window==='undefined'||publicCache.size)return;try{const entries=JSON.parse(sessionStorage.getItem(PUBLIC_PREVIEW_KEY)||'[]');for(const [key,entry] of entries){if(isPublicList(key)&&entry&&Date.now()-entry.time<300000)publicCache.set(key,{...entry,fresh:false});}}catch{}}
function persistPublicCache(){try{sessionStorage.setItem(PUBLIC_PREVIEW_KEY,JSON.stringify([...publicCache].slice(-20)));}catch{}}
const publicRequests=new Map<string,Promise<any>>();
let cacheGeneration=0;
const isPublicList=(path:string)=>['categories','artists','site_settings'].includes(path)||path.startsWith('artworks?')&&!new URLSearchParams(path.split('?')[1]).has('manage');
const cachedData=(path:string)=>{const entry=publicCache.get(path);return entry&&Date.now()-entry.time<300000?entry.data:null;};
function clearPublicCache(){cacheGeneration++;publicCache.clear();publicRequests.clear();try{sessionStorage.removeItem(PUBLIC_PREVIEW_KEY);}catch{}}
function loadData(path:string,force=false){
 if(!isPublicList(path))return api(path);
 const cached=publicCache.get(path);if(!force&&cached?.fresh&&Date.now()-cached.time<10000)return Promise.resolve(cached.data);
 const pending=publicRequests.get(path);if(pending)return pending;
 const generation=cacheGeneration;
 const request=api(path).then(data=>{if(generation===cacheGeneration){publicCache.set(path,{data,time:Date.now(),fresh:true});if(publicCache.size>50)publicCache.delete(publicCache.keys().next().value!);persistPublicCache();}return data;}).finally(()=>{if(publicRequests.get(path)===request)publicRequests.delete(path);});
 publicRequests.set(path,request);return request;
}
export function useData(path:string){
 const [state,setState]=useState<{path:string,data:any}>(()=>({path,data:isPublicList(path)?cachedData(path):null}));const [error,setError]=useState('');const [version,setVersion]=useState(0);
 const data=state.path===path?state.data:isPublicList(path)?cachedData(path):null;
 useEffect(()=>{let live=true;let timer:ReturnType<typeof setTimeout>;setError('');restorePublicCache();setState(current=>({path,data:current.path===path?current.data??(isPublicList(path)?cachedData(path):null):isPublicList(path)?cachedData(path):null}));
 const load=(attempt=0)=>loadData(path,version>0).then(value=>{if(live)setState({path,data:value});}).catch((e:Error&{status?:number})=>{if(!live)return;if(attempt<2&&(!e.status||e.status>=500)){timer=setTimeout(()=>load(attempt+1),500*(attempt+1));return;}setError(e.message);});load();const retry=()=>{setError('');load();};window.addEventListener('sillapa:retry',retry);const revalidate=()=>{if(document.visibilityState==='visible'&&(!isPublicList(path)||Date.now()-(publicCache.get(path)?.time||0)>30000))load();};window.addEventListener('focus',revalidate);document.addEventListener('visibilitychange',revalidate);return()=>{live=false;clearTimeout(timer);window.removeEventListener('sillapa:retry',retry);window.removeEventListener('focus',revalidate);document.removeEventListener('visibilitychange',revalidate);};},[path,version]);
 return {data,error,reload:()=>setVersion(v=>v+1)};
}
export function useDebouncedValue(value:string,delay=200){const [settled,setSettled]=useState(value);useEffect(()=>{const timer=setTimeout(()=>setSettled(value),delay);return()=>clearTimeout(timer);},[value,delay]);return settled;}
export const AppContext=createContext<any>(null);
export function useDraftState(key:string,initial=''):[string,Dispatch<SetStateAction<string>>]{
 const app=useContext(AppContext);const storageKey=`sillapa-draft:${app?.user?.id||'guest'}:${key}`;const [value,setValue]=useState(initial);const [readyKey,setReadyKey]=useState<string|null>(null);
 useEffect(()=>{let saved=initial;try{saved=sessionStorage.getItem(storageKey)??initial;}catch{}setValue(saved);setReadyKey(storageKey);},[storageKey,initial]);
 useEffect(()=>{if(readyKey===storageKey)try{sessionStorage.setItem(storageKey,value);}catch{}},[storageKey,value,readyKey]);return [value,setValue];
}

export function AppProvider({children,initialSession}:{children:ReactNode,initialSession?:any}){
 const [session,setSession]=useState<any>(initialSession??null);const [sessionError,setSessionError]=useState('');const [cart,setCart]=useState<string[]>([]);const [ready,setReady]=useState(false);const [toast,setToast]=useState('');const sessionRequest=useRef(0);
 const refreshSession=useCallback(async()=>{const request=++sessionRequest.current;try{const data=await api('session',{cache:'no-store'});if(request===sessionRequest.current){setSession(data);setSessionError('');}return data;}catch(e:any){if(request===sessionRequest.current)setSessionError(e.message);return null;}},[]);
 useEffect(()=>{if(!initialSession)refreshSession();try{const stored=JSON.parse(localStorage.getItem('sillapa-cart')||'[]');if(Array.isArray(stored))setCart(stored.filter(v=>typeof v==='string').slice(0,20));}catch{}setReady(true);},[refreshSession]);
 useEffect(()=>{let last=Date.now();const retry=()=>{void refreshSession();};const focus=()=>{if(Date.now()-last>30000){last=Date.now();retry();}};window.addEventListener('sillapa:retry',retry);window.addEventListener('focus',focus);return()=>{window.removeEventListener('sillapa:retry',retry);window.removeEventListener('focus',focus);};},[refreshSession]);
 useEffect(()=>{if(ready){try{localStorage.setItem('sillapa-cart',JSON.stringify(cart));}catch{}}},[cart,ready]);
 useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(timer);}},[toast]);
 const logout=async()=>{await send('auth/logout',{});sessionRequest.current++;setSession((current:any)=>({...current,user:null}));setSessionError('');};
 const addToCart=(id:string)=>{setCart(current=>current.includes(id)?current:[...current,id]);setToast('เพิ่มผลงานในตะกร้าแล้ว');};
 return <AppContext.Provider value={{user:session?.user,session,sessionError,cart,ready,setCart,addToCart,notify:setToast,refreshSession,logout}}><Suspense fallback={null}><NavigationFeedback/></Suspense>{children}{toast&&<div className="toast" role="status" aria-live="polite" aria-atomic="true"><Check size={19}/>{toast}</div>}</AppContext.Provider>;
}

function NavigationFeedback(){const path=usePathname();const query=useSearchParams();const [pending,setPending]=useState(false);useEffect(()=>{setPending(false);},[path,query]);useEffect(()=>{let delay:ReturnType<typeof setTimeout>;let stop:ReturnType<typeof setTimeout>;const click=(event:MouseEvent)=>{if(event.defaultPrevented||event.ctrlKey||event.metaKey||event.shiftKey||event.altKey)return;const link=(event.target as Element)?.closest?.('a');if(!link||link.target==='_blank'||link.hasAttribute('download'))return;const next=new URL(link.href,location.href);if(next.origin!==location.origin||next.pathname+next.search===location.pathname+location.search)return;delay=setTimeout(()=>setPending(true),120);stop=setTimeout(()=>setPending(false),10000);};document.addEventListener('click',click);return()=>{document.removeEventListener('click',click);clearTimeout(delay);clearTimeout(stop);};},[path,query]);return pending?<div className="navigation-progress" role="status" aria-label="กำลังเปิดหน้า"><span className="sr-only">กำลังเปิดหน้า</span></div>:null;}
export const useApp=()=>useContext(AppContext);
export function Badge({status}:{status:string}){return <span className={`badge ${status}`}>{statusNames[status]||status}</span>;}
export function Loading({variant='rows'}:{variant?:'rows'|'gallery'|'compact'}){return <div className={`skeleton-loading ${variant==='gallery'?'art-grid skeleton-gallery':variant==='compact'?'skeleton-rows skeleton-compact':'skeleton-rows'}`} role="status" aria-label="กำลังโหลด"><span className="sr-only">กำลังโหลด</span>{Array.from({length:variant==='gallery'?6:variant==='compact'?1:3},(_,i)=><div className="skeleton-item" key={i} aria-hidden="true">{variant==='gallery'&&<div className="skeleton-block skeleton-image"/>}<div className="skeleton-block skeleton-line"/><div className="skeleton-block skeleton-line short"/></div>)}</div>;}
export function ErrorBox({text}:{text:string}){return text?<div className="error-feedback"><p className="error" role="alert">{text}</p>{/ระบบ|โหลด|เชื่อมต่อ|ชั่วคราว/.test(text)&&<button type="button" className="text-button" onClick={()=>window.dispatchEvent(new Event('sillapa:retry'))}>ลองอีกครั้ง</button>}</div>:null;}
export function Empty({title='ยังไม่มีรายการ',children}:{title?:string,children?:ReactNode}){return <div className="empty"><div className="empty-symbol">✳</div><h3>{title}</h3>{children}</div>;}
export function Pagination({data,page,onChange}:{data:any,page:number,onChange:(page:number)=>void}){return data?.pages>1?<div className="pagination"><button className="icon-button" aria-label="หน้าก่อนหน้า" disabled={page<=1} onClick={()=>onChange(page-1)}><ChevronLeft size={18}/></button><span>หน้า {page} จาก {data.pages}</span><button className="icon-button" aria-label="หน้าถัดไป" disabled={page>=data.pages} onClick={()=>onChange(page+1)}><ChevronRight size={18}/></button></div>:null;}
export function Modal({title,children,onClose}:{title:string,children:ReactNode,onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);const dirty=useRef(false);const [discard,setDiscard]=useState(false);useEffect(()=>{if(discard)(ref.current?.querySelector('.discard-confirm button') as HTMLButtonElement|null)?.focus();},[discard]);const close=()=>{if(dirty.current){setDiscard(true);return;}onClose();};useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const dialog=ref.current;dialog?.showModal();(dialog?.querySelector('input:not([type=file]),textarea,select') as HTMLElement|null)?.focus();return()=>{dialog?.close();if(previous?.isConnected)previous.focus();};},[]);return <dialog ref={ref} onInputCapture={()=>{dirty.current=true;}} onChangeCapture={()=>{dirty.current=true;}} onCancel={e=>{e.preventDefault();close();}} aria-labelledby="dialog-title" onClick={e=>{if(e.target===e.currentTarget)close();}} onClickCapture={e=>{const button=(e.target as Element).closest('button');if(dirty.current&&button?.textContent?.trim()==='ยกเลิก'){e.preventDefault();e.stopPropagation();close();}}}><div className="modal-head"><h2 id="dialog-title">{title}</h2><button type="button" className="icon-button" aria-label="ปิดหน้าต่าง" onClick={close}><X size={20}/></button></div>{discard&&<div className="discard-confirm" role="alert"><p>มีข้อมูลที่ยังไม่ได้บันทึก ต้องการปิดหน้าต่างหรือไม่?</p><div className="row-actions"><button type="button" className="button" onClick={()=>{setDiscard(false);(ref.current?.querySelector('input,textarea,select') as HTMLElement|null)?.focus();}}>แก้ไขต่อ</button><button type="button" className="button danger" onClick={onClose}>ทิ้งการแก้ไข</button></div></div>}{children}</dialog>;}
export function Upload({kind,onUploaded,label}:{label?:string,kind:'art'|'slip'|'profile'|'banner',onUploaded:(data:any)=>void}){const [busy,setBusy]=useState(false);const [error,setError]=useState('');return <div><label className={`upload ${busy?'disabled':''}`}><ImagePlus size={24}/><strong>{busy?'กำลังอัปโหลด…':label|| (kind==='banner'?'เลือกภาพโปสเตอร์':kind==='art'?'เลือกภาพผลงาน':kind==='profile'?'เลือกภาพโปรไฟล์':'เลือกภาพสลิปการชำระเงิน')}</strong><span>JPG, PNG หรือ WebP · ไม่เกิน 3 MB</span><input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');try{const form=new FormData();form.set('file',file);form.set('kind',kind);const data=await api('upload',{method:'POST',body:form});onUploaded(data);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}/></label><ErrorBox text={error}/></div>;}
