import { z } from 'zod';
const text = (min: number,max: number) => z.string().trim().min(min,`กรุณากรอกอย่างน้อย ${min} ตัวอักษร`).max(max,`ต้องไม่เกิน ${max} ตัวอักษร`);
export const loginSchema = z.object({email:z.email('อีเมลไม่ถูกต้อง').trim().toLowerCase(),password:z.string().min(1).max(128)});
export const registerSchema = loginSchema.extend({name:text(2,100),password:z.string().min(10,'รหัสผ่านต้องมีอย่างน้อย 10 ตัวอักษร').max(128),artist_requested:z.boolean().default(false)});
export const artworkSchema = z.object({title:text(2,150),description:text(10,3000),category_id:text(1,100),technique:text(2,100),width:z.coerce.number().positive().max(1000),height:z.coerce.number().positive().max(1000),price:z.coerce.number().positive().max(1000000).refine(v=>Math.abs(v*100-Math.round(v*100))<0.000001,'ราคาใส่ทศนิยมได้ไม่เกิน 2 ตำแหน่ง'),image:z.string().regex(/^\/api\/media\/[a-f0-9-]{36}$|^\/art\/art-[1-8]\.jpg$/,'กรุณาอัปโหลดภาพผลงาน')});
export const orderSchema = z.object({artwork_ids:z.array(text(1,100)).min(1).max(20).refine(v=>new Set(v).size===v.length,'ผลงานซ้ำในตะกร้า'),address_id:z.uuid().optional(),recipient:text(2,100).optional(),phone:z.string().regex(/^0\d{8,9}$/,'เบอร์โทรศัพท์ไม่ถูกต้อง').optional(),address:text(15,600).optional(),payment_method:z.enum(['promptpay','bank_transfer']).default('promptpay'),buyer_note:text(0,300).default(''),idempotency_key:z.uuid()}).refine(v=>!!v.address_id || !!(v.recipient&&v.phone&&v.address),'กรุณาเลือกที่อยู่จัดส่ง');
export const addressSchema=z.object({recipient:text(2,100),phone:z.string().regex(/^0\d{8,9}$/,'เบอร์โทรศัพท์ไม่ถูกต้อง'),line1:text(5,300),province:text(2,80),district:text(2,80),subdistrict:text(2,80),postcode:z.string().regex(/^\d{5}$/,'รหัสไปรษณีย์ต้องมี 5 หลัก'),label:z.enum(['home','work','other']).default('home'),is_default:z.boolean().default(false)});
export const profileSchema = z.object({name:text(2,100),bio:text(0,1000),university:text(0,150),artist_requested:z.boolean().optional()});
export const userSchema = z.object({name:text(2,100),role:z.enum(['admin','staff','customer']),active:z.boolean()});
