import { chromium, expect } from '@playwright/test';
import { spawn } from 'node:child_process';
import path from 'node:path';
import { mkdir, writeFile } from 'node:fs/promises';
const port=3101, origin=`http://localhost:${port}`;
const server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','-p',String(port)],{cwd:process.cwd(),env:{...process.env,BLOB_READ_WRITE_TOKEN:'',VERCEL:'',APP_URL:origin,LOCAL_DB_PATH:path.join(process.cwd(),'.data','tests',`browser-${Date.now()}`),PROMPTPAY_ID:'',PROMPTPAY_NAME:''},stdio:'pipe',windowsHide:true});
let serverLog='';server.stdout.on('data',d=>serverLog+=d);server.stderr.on('data',d=>serverLog+=d);
const results:string[]=[];const errors:string[]=[];
async function main(){
 for(let i=0;i<90;i++){try{if((await fetch(`${origin}/api/session`)).ok)break;}catch{}if(i===89)throw new Error(serverLog);await new Promise(r=>setTimeout(r,1000));}
 await mkdir('docs/screenshots',{recursive:true});
 const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||'msedge',headless:true});
 try{
 const customer=await browser.newContext({viewport:{width:1440,height:1000}});const page=await customer.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`${origin}/register`);await page.locator('.auth-form form button').click();await expect(page.locator('.field-error')).toHaveCount(3);await expect(page.locator('.error')).toHaveCount(0);expect(await page.locator('.field-error').first().evaluate(el=>getComputedStyle(el).color)).toBe('rgb(198, 40, 40)');results.push('Invalid registration fields show calm inline red text without an alert card');
 await page.goto(origin);await expect(page.locator('.art-card')).toHaveCount(7);await page.screenshot({path:'docs/screenshots/gallery-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'ตัวกรอง',exact:true}).click();await page.getByPlaceholder('ชื่อผลงานหรือศิลปิน').fill('วันจันทร์');await expect(page.locator('.art-card')).toHaveCount(1);
 await page.getByRole('button',{name:'ล้างทั้งหมด',exact:true}).click();await expect(page.locator('.art-card')).toHaveCount(7);
 await page.getByLabel('เรียงผลงาน').selectOption('price_asc');await expect(page.locator('.art-bottom strong').first()).toContainText('2,600');await page.getByRole('button',{name:'ตัวกรอง',exact:true}).click();results.push('Gallery search, reset and sorting operate in the browser');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'docs/screenshots/gallery-mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await page.getByRole('button',{name:'ตัวกรอง',exact:true}).click();await expect(page.getByPlaceholder('ชื่อผลงานหรือศิลปิน')).toBeVisible();
 await page.getByRole('button',{name:'ตัวกรอง',exact:true}).click();await page.setViewportSize({width:1440,height:1000});results.push('Mobile gallery fits 390px width and filters can be expanded');
 await page.goto(`${origin}/login`);await page.getByRole('button',{name:'ลูกค้า',exact:true}).click();await page.getByRole('button',{name:'เข้าสู่ระบบ',exact:true}).click();await expect(page).toHaveURL(origin+'/');
 await expect(page.locator('.gallery-intro')).toBeVisible();await expect(page.locator('.art-card')).toHaveCount(7);await page.reload();await expect(page.locator('.account')).toBeVisible();results.push('Customer retains login after reload and uses the same gallery home as guests');
 await page.locator('.main-nav').getByRole('link',{name:'ภาพวาด',exact:true}).click();await expect(page).toHaveURL(/category=painting/);await expect(page.locator('.category-tabs .selected')).toHaveText('จิตรกรรม');await expect(page.locator('.art-card')).toHaveCount(1);await expect(page.locator('.gallery-intro')).toHaveCount(0);
 await page.locator('.main-nav').getByRole('link',{name:'ภาพประกอบ',exact:true}).click();await expect(page.locator('.category-tabs .selected')).toHaveText('ภาพประกอบ');await expect(page.getByRole('heading',{name:'ไม่พบผลงานที่ค้นหา'})).toBeVisible();await page.reload();await expect(page.locator('.category-tabs .selected')).toHaveText('ภาพประกอบ');results.push('Navigation categories filter results, retain selection after reload and show an honest empty state');
 await page.goto(`${origin}/artworks/sample-1`);await page.getByRole('button',{name:'เพิ่มลงตะกร้า',exact:true}).click();await page.getByRole('link',{name:'ไปที่ตะกร้า',exact:true}).click();
 await page.getByRole('button',{name:'เพิ่มที่อยู่จัดส่ง',exact:true}).click();await page.getByLabel('ชื่อผู้รับ',{exact:true}).fill('ทดสอบ ผู้ซื้อ');await page.getByLabel('เบอร์โทรศัพท์',{exact:true}).fill('0812345678');await page.getByLabel('บ้านเลขที่ / อาคาร / ถนน',{exact:true}).fill('123 ถนนมิตรภาพ');
 await page.getByRole('combobox',{name:'จังหวัด',exact:true}).selectOption('ขอนแก่น');await page.getByRole('combobox',{name:'อำเภอ / เขต',exact:true}).selectOption('เมืองขอนแก่น');await page.getByRole('combobox',{name:'ตำบล / แขวง',exact:true}).selectOption('ในเมือง');await expect(page.getByRole('combobox',{name:'รหัสไปรษณีย์',exact:true})).toHaveValue('40000');await page.getByRole('button',{name:'บันทึกที่อยู่',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('.selected-address')).toContainText('40000');
 await page.getByRole('button',{name:'เปลี่ยน',exact:true}).click();await page.getByRole('button',{name:'เพิ่มที่อยู่ใหม่',exact:true}).click();await page.getByLabel('ชื่อผู้รับ',{exact:true}).fill('ผู้รับที่ทำงาน');await page.getByLabel('เบอร์โทรศัพท์',{exact:true}).fill('0898765432');await page.getByLabel('บ้านเลขที่ / อาคาร / ถนน',{exact:true}).fill('456 อาคารทดสอบ');await page.getByRole('combobox',{name:'จังหวัด',exact:true}).selectOption('ขอนแก่น');await page.getByRole('combobox',{name:'อำเภอ / เขต',exact:true}).selectOption('เมืองขอนแก่น');await page.getByRole('combobox',{name:'ตำบล / แขวง',exact:true}).selectOption('ในเมือง');await expect(page.getByRole('combobox',{name:'รหัสไปรษณีย์',exact:true})).toHaveValue('40000');await page.getByRole('radio',{name:'ที่ทำงาน',exact:true}).check();await page.getByRole('button',{name:'บันทึกที่อยู่',exact:true}).click();await expect(page.locator('.selected-address')).toContainText('456 อาคารทดสอบ');
 await page.getByRole('button',{name:'เปลี่ยน',exact:true}).click();await page.getByRole('radio',{name:/เลือกที่อยู่ ทดสอบ ผู้ซื้อ/}).check();await page.getByRole('button',{name:'ใช้ที่อยู่นี้',exact:true}).click();await expect(page.locator('.selected-address')).toContainText('123 ถนนมิตรภาพ');
 const addressPage=await customer.newPage();await addressPage.goto(`${origin}/addresses`);const workAddress=addressPage.locator('.saved-address').filter({hasText:'456 อาคารทดสอบ'});await workAddress.getByRole('button',{name:'ตั้งเป็นค่าเริ่มต้น',exact:true}).click();await expect(workAddress.locator('.default-tag')).toBeVisible();await addressPage.reload();await expect(workAddress.locator('.default-tag')).toBeVisible();await addressPage.close();await page.reload();await expect(page.locator('.selected-address')).toContainText('456 อาคารทดสอบ');results.push('New non-default address stays selected; address picker works; default address persists after reload');
 await page.getByRole('radio',{name:/โอนผ่านบัญชีธนาคาร/}).check();await expect(page.locator('.summary-method')).toHaveText('โอนผ่านบัญชีธนาคาร');await page.getByRole('radio',{name:/สแกน QR PromptPay/}).check();await page.getByLabel('ข้อความถึงร้าน',{exact:true}).fill('กรุณาห่อกันกระแทก');await page.getByRole('heading',{name:'ชำระเงิน',exact:true}).click();await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:'docs/screenshots/checkout-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:'docs/screenshots/checkout-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});results.push('Checkout saves a structured Thai address, fills postcode, selects payment and fits mobile');
 await page.getByRole('button',{name:'ยืนยันคำสั่งซื้อ',exact:true}).click();await expect(page).toHaveURL(/\/orders\/[a-f0-9-]+/);const orderUrl=page.url();
 await page.locator('input[type=file]').setInputFiles('public/art/art-2.jpg');await expect(page.getByText('แนบสลิปแล้ว · รอตรวจสอบ')).toBeVisible();results.push('Customer logs in, adds an artwork, checks out and uploads a slip');
 const deniedPage=await customer.newPage();await deniedPage.goto(`${origin}/admin`);await expect(deniedPage.getByRole('heading',{name:'สำหรับผู้ดูแลระบบเท่านั้น'})).toBeVisible();await deniedPage.close();results.push('Customer accounts are blocked from the separate admin portal');
 const admin=await browser.newContext({viewport:{width:1440,height:1000}});const adminPage=await admin.newPage();adminPage.on('pageerror',e=>errors.push(e.message));
 await adminPage.goto(`${origin}/admin`);await adminPage.getByLabel('อีเมลผู้ดูแล').fill('admin@demo.local');await adminPage.getByLabel('รหัสผ่าน').fill('ArtDemo2026!');await adminPage.getByRole('button',{name:/เข้าสู่ Admin Portal/,exact:true}).click();await expect(adminPage.getByText('ยอดขายที่รับชำระแล้ว')).toBeVisible();
 await adminPage.goto(orderUrl.replace('/orders/','/admin/orders/'));await adminPage.getByRole('button',{name:'ยืนยันรับชำระเงิน',exact:true}).click();await adminPage.getByLabel('บริษัทขนส่ง / เลขติดตามพัสดุ').fill('TH Post: UI-TEST-001');await adminPage.getByRole('button',{name:'ยืนยันการจัดส่ง',exact:true}).click();await expect(adminPage.locator('.tracking')).toContainText('UI-TEST-001');
 await page.reload();await page.getByRole('button',{name:'ยืนยันว่าได้รับผลงานแล้ว',exact:true}).click();await expect(page.locator('.page-heading .badge')).toHaveText('สำเร็จ');results.push('Admin confirms payment and shipping; customer completes receipt');
 await adminPage.goto(`${origin}/admin`);await expect(adminPage.locator('.stat-card').first()).toContainText('3,200');await adminPage.screenshot({path:'docs/screenshots/dashboard-desktop.png',fullPage:true});
 await adminPage.setViewportSize({width:390,height:844});expect(await adminPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await adminPage.screenshot({path:'docs/screenshots/dashboard-mobile.png',fullPage:true});results.push('Dashboard reflects the paid order and fits mobile width');
 const artist=await browser.newContext({viewport:{width:1440,height:1000}});const artistPage=await artist.newPage();artistPage.on('pageerror',e=>errors.push(e.message));
 await artistPage.goto(`${origin}/login`);await artistPage.getByRole('button',{name:'ศิลปิน',exact:true}).click();await artistPage.getByRole('button',{name:'เข้าสู่ระบบ',exact:true}).click();await expect(artistPage).toHaveURL(origin+'/');
 await artistPage.goto(`${origin}/studio`);await expect(artistPage.getByRole('heading',{name:/สวัสดี/})).toBeVisible();await expect(artistPage.getByRole('link',{name:/อัปโหลดผลงาน/})).toBeVisible();await expect(artistPage.locator('.artist-status-grid>a')).toHaveCount(3);await artistPage.screenshot({path:'docs/screenshots/artist-studio-desktop.png',fullPage:true});await artistPage.setViewportSize({width:390,height:844});expect(await artistPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await artistPage.screenshot({path:'docs/screenshots/artist-studio-mobile.png',fullPage:true});await artistPage.setViewportSize({width:1440,height:1000});results.push('Artist Studio highlights upload, approval states, next actions and fits mobile');
 await artistPage.goto(`${origin}/studio/artworks`);await artistPage.getByRole('button',{name:'เพิ่มผลงาน',exact:true}).click();await artistPage.locator('dialog input[type=file]').setInputFiles('public/art/art-3.jpg');await expect(artistPage.locator('.upload-preview')).toBeVisible();
 await artistPage.getByLabel('ชื่อผลงาน',{exact:true}).fill('ผลงานจากการทดสอบหน้าจอ');await artistPage.locator('select[name=category_id]').selectOption('painting');await artistPage.getByLabel('เทคนิค',{exact:true}).fill('สีน้ำมันบนผ้าใบ');await artistPage.getByLabel('กว้าง (ซม.)').fill('40');await artistPage.getByLabel('สูง (ซม.)').fill('50');await artistPage.getByLabel('ราคา (บาท)').fill('1200');await artistPage.getByLabel('เรื่องราวของผลงาน').fill('ทดสอบการเพิ่มผลงานผ่านแบบฟอร์มจริงพร้อมภาพและรายละเอียด');await artistPage.getByRole('button',{name:'บันทึกและส่งขออนุมัติ'}).click();await expect(artistPage.getByRole('dialog')).toHaveCount(0);await expect(artistPage.getByText('ผลงานจากการทดสอบหน้าจอ',{exact:true})).toBeVisible();
 await adminPage.setViewportSize({width:1440,height:1000});await adminPage.goto(`${origin}/admin/artworks`);const row=adminPage.getByRole('row').filter({hasText:'ผลงานจากการทดสอบหน้าจอ'});await row.getByRole('button',{name:'ตรวจผลงาน'}).click();await adminPage.getByRole('button',{name:'อนุมัติเผยแพร่'}).click();await expect(adminPage.getByRole('dialog')).toHaveCount(0);await expect(row.locator('.badge')).toHaveText('พร้อมจำหน่าย');results.push('Artist uploads and submits art through the form; admin publishes it');
 await adminPage.goto(`${origin}/admin/logs`);await expect(adminPage.locator('tbody tr').first()).toBeVisible();results.push('Audit log is visible in the separate admin portal');
 for(const [role,context,routes] of [
 ['customer',customer,['/','/gallery?category=painting','/gallery?category=illustration','/artists','/artists/demo-artist','/artworks/sample-2','/cart','/orders','/profile','/profiles/demo-customer','/addresses','/credits']],
 ['admin',admin,['/','/profile','/profiles/demo-admin','/admin','/admin/artworks','/admin/orders','/admin/users','/admin/categories','/admin/logs','/studio']],
 ['artist',artist,['/','/profile','/profiles/demo-artist','/artists/demo-artist','/studio','/studio/artworks','/studio/orders']]
 ] as const){const auditPage=await context.newPage();auditPage.on('pageerror',e=>errors.push(e.message));for(const route of routes){console.log('Checking',role,route);await auditPage.goto(origin+route);await expect(auditPage.locator('h1,h2,h3').first()).toBeVisible();await expect(auditPage.locator('.error')).toHaveCount(0);const nav=auditPage.locator(route.startsWith('/admin')?'nav[aria-label="เมนูแอดมิน"]':route.startsWith('/studio')?'nav[aria-label="เมนูจัดการร้าน"]':'.main-nav');await expect(nav.getByRole('link',{name:'คำสั่งซื้อ',exact:true})).toHaveCount(1);await auditPage.setViewportSize({width:390,height:844});expect(await auditPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await auditPage.setViewportSize({width:1440,height:1000});}results.push(`${role}: all ${routes.length} routes render without errors and fit mobile`);await auditPage.close();}
 await page.goto(origin);for(const width of [768,390]){await page.setViewportSize({width,height:900});await page.getByRole('button',{name:'เปิดเมนู',exact:true}).click();await expect(page.locator('.main-nav').getByRole('link',{name:'คำสั่งซื้อ',exact:true})).toBeVisible();await expect(page.locator('.main-nav').getByRole('link',{name:'โปรไฟล์ของฉัน',exact:true})).toBeVisible();await expect(page.locator('.main-nav').getByRole('button',{name:'ออกจากระบบ',exact:true})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'เปิดเมนู',exact:true})).toHaveAttribute('aria-expanded','false');}await page.setViewportSize({width:1440,height:1000});results.push('Tablet/mobile menu exposes orders, profile and logout; Escape closes it');
 await page.goto(`${origin}/profile`);await page.getByLabel('ชื่อที่แสดง',{exact:true}).fill('ลูกค้าทดสอบโปรไฟล์');await page.getByLabel('แนะนำตัว',{exact:true}).fill('ทดสอบแนะนำตัวบนโปรไฟล์สาธารณะ');await page.locator('input[type=color]').fill('#de4567');await page.getByRole('button',{name:'บันทึกโปรไฟล์',exact:true}).click();await expect(page.getByRole('status')).toContainText('บันทึกโปรไฟล์แล้ว');await page.getByRole('link',{name:'ดูโปรไฟล์ของฉัน',exact:true}).click();await expect(page.getByRole('heading',{name:'ลูกค้าทดสอบโปรไฟล์',exact:true})).toBeVisible();await expect(page.getByText('ทดสอบแนะนำตัวบนโปรไฟล์สาธารณะ',{exact:true})).toBeVisible();results.push('Profile customization saves and public profile displays saved content');
 for(const context of [customer,admin,artist]){const logoutPage=await context.newPage();await logoutPage.goto(origin);await logoutPage.getByRole('button',{name:'ออกจากระบบ',exact:true}).click();await expect(logoutPage.getByRole('link',{name:'เข้าสู่ระบบ',exact:true})).toBeVisible();await logoutPage.reload();await expect(logoutPage.getByRole('link',{name:'เข้าสู่ระบบ',exact:true})).toBeVisible();await logoutPage.close();}results.push('Customer, admin and artist logout persists after reload');
 expect(errors).toEqual([]);results.push('No browser runtime errors during tested journeys');
 await writeFile('docs/BROWSER-RESULTS.md',`# Browser verification\n\nExecuted: ${new Date().toISOString()}\n\nMicrosoft Edge via Playwright, isolated production server/database; no actual payment.\n\n${results.map(r=>`- PASS: ${r}`).join('\n')}\n\nScreenshots: gallery, customer home, artist Studio and admin dashboard at desktop and 390px mobile widths.\n`);console.log(results.map(r=>`PASS ${r}`).join('\n'));
 }finally{await browser.close();}
}
main().catch(e=>{console.error(e);console.error(serverLog.slice(-1500));process.exitCode=1;}).finally(()=>server.kill());
