import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
const origin='http://localhost:3100';
const stamp=Date.now();
const results:string[]=[];
let serverLog='';
const server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','-p','3100'],{cwd:process.cwd(),env:{...process.env,DATABASE_URL:'',VERCEL:'',APP_URL:origin,LOCAL_DB_PATH:path.join(process.cwd(),'.data','tests',String(stamp)),PROMPTPAY_ID:'0812345678',PROMPTPAY_NAME:'TEST ONLY — DO NOT TRANSFER'},stdio:['ignore','pipe','pipe'],windowsHide:true});
server.stdout.on('data',d=>serverLog+=d);server.stderr.on('data',d=>serverLog+=d);
class Client {
 cookie='';
 async request(route:string,method='GET',data?:any,expected=200,customOrigin=origin){
  const headers:Record<string,string>={origin:customOrigin};if(this.cookie)headers.cookie=this.cookie;
  if(!(data instanceof FormData))headers['content-type']='application/json';
  const res=await fetch(`${origin}/api/${route}`,{method,headers,body:data===undefined?undefined:data instanceof FormData?data:JSON.stringify(data)});
  const cookie=res.headers.get('set-cookie');if(cookie)this.cookie=cookie.split(';')[0];
  const text=await res.text();let body;try{body=JSON.parse(text);}catch{body=text;}
  assert.equal(res.status,expected,`${method} ${route}: ${text.slice(0,500)}`);return body;
 }
 login(email:string,password='ArtDemo2026!'){return this.request('auth/login','POST',{email,password});}
}
function pass(label:string){results.push(label);console.log(`PASS ${label}`);}
async function main(){
 for(let i=0;i<90;i++){try{const r=await fetch(`${origin}/api/session`);if(r.ok)break;}catch{}if(i===89)throw new Error(`Server failed to start: ${serverLog}`);await new Promise(r=>setTimeout(r,1000));}
 const guest=new Client(),admin=new Client(),artist=new Client(),customer=new Client(),other=new Client();
 await admin.login('admin@demo.local');await artist.login('artist@demo.local');await customer.login('customer@demo.local');
 await other.request('auth/register','POST',{name:'Integration Customer',email:`test-${stamp}@example.test`,password:'IntegrationPass!2026',role:'admin',artist_requested:true},201);
 assert.equal((await other.request('session')).user.role,'customer');pass('Registration ignores injected role; new users are customers');
 await guest.request('users','GET',undefined,401);await customer.request('users','GET',undefined,403);await customer.request('dashboard','GET',undefined,403);await customer.request('logs','GET',undefined,403);
 await artist.request('users','GET',undefined,403);pass('Server-side role checks protect users, reports and audit logs');
 await admin.request('categories','POST',{name:'Blocked CSRF'},403,'https://evil.example');pass('Cross-origin writes rejected');
 await guest.request('auth/login','POST',{email:'admin@demo.local',password:'wrong'},401);
 await guest.request('auth/register','POST',{name:'A',email:'invalid',password:'short'},400);pass('Invalid login and registration validation');
 const publicList=await guest.request('artworks');assert.equal(publicList.total,7);
 await guest.request('artworks/sample-8','GET',undefined,404);
 assert.equal((await artist.request('artworks?manage=true')).items.every((a:any)=>a.artist_id==='demo-artist'),true);
 await artist.request('artworks/sample-2','DELETE',undefined,403);pass('Pending art is private; artists cannot edit another artist’s work');
 const form=new FormData();form.set('file',new Blob([await readFile('public/art/art-1.jpg')],{type:'image/jpeg'}),'test.jpg');form.set('kind','art');
 const uploaded=await artist.request('upload','POST',form,201);
 const hiddenMedia=await fetch(`${origin}${uploaded.url}`);assert.equal(hiddenMedia.status,404);
 const badForm=new FormData();badForm.set('file',new Blob(['not an image'],{type:'image/jpeg'}),'fake.jpg');badForm.set('kind','art');await artist.request('upload','POST',badForm,400);
 await customer.request('upload','POST',form,403);pass('Uploads validate actual image bytes, size/type and uploader role; drafts stay private');
 await admin.request('categories','POST',{name:`Test category ${stamp}`});const cats=await admin.request('categories');const category=cats.items.find((c:any)=>c.name===`Test category ${stamp}`);
 await admin.request(`categories/${category.id}`,'PATCH',{name:`Renamed category ${stamp}`});
 const art={title:'Integration artwork',description:'A meaningful integration testing artwork description.',category_id:category.id,technique:'Oil on canvas',width:50,height:60,price:1234.56,image:uploaded.url};
 await artist.request('artworks','POST',{...art,price:-1},400);const created=await artist.request('artworks','POST',art,201);const id=created.id;
 await admin.request(`categories/${category.id}`,'DELETE',undefined,409);
 await customer.request(`artworks/${id}/review`,'PATCH',{status:'approved'},403);
 await admin.request(`artworks/${id}/review`,'PATCH',{status:'rejected',note:'Please improve the description.'});
 assert.equal((await artist.request(`artworks/${id}`)).artwork.status,'rejected');
 await artist.request(`artworks/${id}`,'PATCH',{...art,title:'Integration updated artwork'});
 assert.equal((await artist.request(`artworks/${id}`)).artwork.status,'pending');
 await admin.request(`artworks/${id}/review`,'PATCH',{status:'approved'});
 assert.equal((await fetch(`${origin}${uploaded.url}`)).status,200);pass('Artwork/category CRUD, validation, review and draft-to-public transitions');
 const filtered=await guest.request(`artworks?q=Integration&category=${category.id}&sort=price_asc&max=1300`);assert.equal(filtered.total,1);assert.equal(filtered.items[0].price,123456);
 const sorted=await guest.request('artworks?sort=price_asc');for(let i=1;i<sorted.items.length;i++)assert.ok(sorted.items[i].price>=sorted.items[i-1].price);
 const extraIds=[];for(let i=0;i<7;i++){const a=await artist.request('artworks','POST',{...art,title:`Pagination artwork ${i}`},201);extraIds.push(a.id);await admin.request(`artworks/${a.id}/review`,'PATCH',{status:'approved'});}
 const p1=await guest.request('artworks?page=1'),p2=await guest.request('artworks?page=2');assert.equal(p1.items.length,12);assert.ok(p2.items.length>0);assert.equal(p1.items.some((a:any)=>p2.items.some((b:any)=>b.id===a.id)),false);
 pass('Search, category/price filters, price sort and non-overlapping pagination');
 const location=await guest.request('geography?province='+encodeURIComponent('ขอนแก่น')+'&district='+encodeURIComponent('เมืองขอนแก่น')+'&subdistrict='+encodeURIComponent('ในเมือง'));
 assert.ok(location.postcodes.includes('40000'));assert.equal((await guest.request('geography')).provinces.length,77);
 await guest.request('addresses','GET',undefined,401);
 const addressValue={recipient:'Saved Recipient',phone:'0812345678',line1:'123 ถนนมิตรภาพ',province:'ขอนแก่น',district:'เมืองขอนแก่น',subdistrict:'ในเมือง',postcode:'40000',label:'home',is_default:false};
 await customer.request('addresses','POST',{...addressValue,postcode:'99999'},400);
 const saved=await customer.request('addresses','POST',addressValue,201);assert.equal((await customer.request('addresses')).items[0].is_default,true);
 const second=await customer.request('addresses','POST',{...addressValue,line1:'456 ถนนทดสอบ',label:'work',is_default:true},201);
 let savedList=(await customer.request('addresses')).items;assert.equal(savedList.filter((a:any)=>a.is_default).length,1);assert.equal(savedList[0].id,second.id);
 assert.equal((await other.request('addresses')).items.length,0);
 await other.request(`addresses/${saved.id}`,'PATCH',addressValue,404);await other.request(`addresses/${saved.id}`,'DELETE',undefined,404);
 const addressOrder={artwork_ids:[extraIds[1]],address_id:saved.id,payment_method:'bank_transfer',buyer_note:'Please protect the frame.',idempotency_key:randomUUID(),total:1,shipping_fee:999999};
 await other.request('orders','POST',addressOrder,404);
 await customer.request('orders','POST',{...addressOrder,payment_method:'credit_card'},400);
 const bankOrder=await customer.request('orders','POST',addressOrder,201);
 await customer.request(`addresses/${saved.id}`,'PATCH',{...addressValue,line1:'789 Changed street'});
 const bankDetail=await customer.request(`orders/${bankOrder.id}`);assert.equal(bankDetail.order.payment_method,'bank_transfer');assert.equal(bankDetail.qr,null);assert.equal(bankDetail.order.recipient,'Saved Recipient');assert.match(bankDetail.order.address,/123/);assert.equal(bankDetail.order.shipping_fee,0);assert.equal(bankDetail.order.total,123456);assert.equal(bankDetail.order.buyer_note,'Please protect the frame.');
 await customer.request(`orders/${bankOrder.id}/status`,'PATCH',{status:'cancelled'});
 await customer.request(`addresses/${second.id}`,'DELETE');savedList=(await customer.request('addresses')).items;assert.equal(savedList.length,1);assert.equal(savedList[0].is_default,true);
 pass('Saved addresses: Thai geography validation, ownership, one default, deletion fallback and immutable order snapshot');
 pass('Checkout stores bank payment and buyer note; server controls shipping/total and rejects unsupported payment');
 const orderInput={artwork_ids:[id],recipient:'Integration Recipient',phone:'0812345678',address:'123 Test Road, Bangkok 10100, Thailand',idempotency_key:randomUUID(),total:1};
 const order=await customer.request('orders','POST',orderInput,201);
 assert.equal((await customer.request('orders','POST',orderInput)).id,order.id);
 const detail=await customer.request(`orders/${order.id}`);assert.equal(detail.order.total,123456);assert.match(detail.qr,/^data:image\/png;base64,/);
 await other.request('orders','POST',{...orderInput,idempotency_key:randomUUID()},409);
 await other.request(`orders/${order.id}`,'GET',undefined,404);await artist.request(`orders/${order.id}`,'GET',undefined,404);
 await artist.request(`artworks/${id}`,'DELETE',undefined,409);pass('Checkout computes price on server; idempotency, reservation and private orders enforced');
 await customer.request(`orders/${order.id}/status`,'PATCH',{status:'paid'},409);
 await admin.request(`orders/${order.id}/status`,'PATCH',{status:'shipped',tracking:'test'},409);
 const slipForm=new FormData();slipForm.set('file',new Blob([await readFile('public/art/art-2.jpg')],{type:'image/jpeg'}),'test-slip.jpg');slipForm.set('kind','slip');
 let slip=await customer.request('upload','POST',slipForm,201);await customer.request(`orders/${order.id}/slip`,'PATCH',{slip_id:slip.id});
 await other.request(`media/${slip.id}`,'GET',undefined,404);await guest.request(`media/${slip.id}`,'GET',undefined,404);await artist.request(`media/${slip.id}`,'GET',undefined,404);
 await customer.request(`orders/${order.id}/status`,'PATCH',{status:'paid'},409);
 await admin.request(`orders/${order.id}/status`,'PATCH',{status:'reject_slip',note:'Test slip rejection'});
 assert.equal((await customer.request(`orders/${order.id}`)).order.slip_id,null);
 slip=await customer.request('upload','POST',slipForm,201);await customer.request(`orders/${order.id}/slip`,'PATCH',{slip_id:slip.id});
 await admin.request(`orders/${order.id}/status`,'PATCH',{status:'paid'});
 assert.equal((await guest.request(`artworks/${id}`)).artwork.status,'sold');
 await admin.request(`orders/${order.id}/status`,'PATCH',{status:'shipped',tracking:''},409);
 await admin.request(`orders/${order.id}/status`,'PATCH',{status:'shipped',tracking:'TEST-TRACK-001'});
 await customer.request(`orders/${order.id}/status`,'PATCH',{status:'completed'});
 assert.equal((await customer.request(`orders/${order.id}`)).order.status,'completed');pass('Private slips, rejection/re-upload, admin-only payment confirmation and shipping workflow');
 const racingId=extraIds[0];const races=await Promise.all([customer,other].map(async c=>{const res=await fetch(`${origin}/api/orders`,{method:'POST',headers:{origin,'content-type':'application/json',cookie:c.cookie},body:JSON.stringify({...orderInput,artwork_ids:[racingId],idempotency_key:randomUUID()})});return {status:res.status,body:await res.json(),client:c};}));
 assert.deepEqual(races.map(r=>r.status).sort(),[201,409]);const winner=races.find(r=>r.status===201)!;await winner.client.request(`orders/${winner.body.id}/status`,'PATCH',{status:'cancelled'});assert.equal((await guest.request(`artworks/${racingId}`)).artwork.status,'approved');pass('Concurrent purchases have exactly one winner; cancellation releases inventory');
 const dash=await admin.request('dashboard');assert.equal(Number(dash.stats.revenue),123456);assert.equal(dash.stats.orders,1);assert.equal(dash.artists.length,1);
 const logs=await admin.request('logs');assert.ok(logs.total>20);assert.ok(logs.items.some((l:any)=>l.action==='status_change'));pass('Dashboard totals and transactional audit trail match completed operations');
 const otherUser=(await other.request('session')).user;
 await other.request('profile','PATCH',{name:'Requested artist',bio:'Hello, I paint.',university:'Demo university',artist_requested:true});
 await admin.request(`users/${otherUser.id}`,'PATCH',{name:'Approved artist',role:'staff',active:true});assert.equal((await other.request('session')).user,null);
 await other.login(`test-${stamp}@example.test`,'IntegrationPass!2026');assert.equal((await other.request('session')).user.role,'staff');
 await admin.request(`users/${otherUser.id}`,'PATCH',{name:'Approved artist',role:'staff',active:false});assert.equal((await other.request('session')).user,null);
 await admin.request('users/demo-admin','PATCH',{name:'Admin',role:'customer',active:true},400);pass('Profile requests, role promotion, session invalidation, deactivation and self-lockout prevention');
 const temporary=await artist.request('artworks','POST',{...art,title:'Delete test artwork'},201);await artist.request(`artworks/${temporary.id}`,'DELETE');await artist.request(`artworks/${temporary.id}`,'GET',undefined,404);
 await admin.request('categories','POST',{name:`Unused category ${stamp}`});const unused=(await admin.request('categories')).items.find((c:any)=>c.name===`Unused category ${stamp}`);await admin.request(`categories/${unused.id}`,'DELETE');pass('Artwork soft deletion and unused category deletion');
 const logoutCookie=customer.cookie;await customer.request('auth/logout','POST',{});customer.cookie=logoutCookie;await customer.request('orders','GET',undefined,401);pass('Logout invalidates server-side session');
 await mkdir('docs',{recursive:true});await writeFile('docs/TEST-RESULTS.md',`# Integration test results\n\nExecuted: ${new Date().toISOString()}\n\nProduction Next.js server with isolated persistent PostgreSQL (PGlite) database. No live payment sent.\n\n${results.map(r=>`- PASS: ${r}`).join('\n')}\n\n${results.length} groups passed. Remote Supabase connectivity and Vercel deployment are not covered without owner credentials.\n`);
 console.log(`\n${results.length} test groups passed.`);
}
main().catch(e=>{console.error(e);console.error(serverLog.slice(-5000));process.exitCode=1;}).finally(()=>{server.kill();});
